/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.ssglobal.revalida.codes.model.tables.Admin;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminRecord extends UpdatableRecordImpl<AdminRecord> implements Record9<Integer, String, String, String, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 382930071;

    /**
     * Setter for <code>public.admin.admin_id</code>.
     */
    public AdminRecord setAdminId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.admin.admin_id</code>.
     */
    public Integer getAdminId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.admin.username</code>.
     */
    public AdminRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.admin.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.admin.password</code>.
     */
    public AdminRecord setPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.admin.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.admin.firstname</code>.
     */
    public AdminRecord setFirstname(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.admin.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.admin.lastname</code>.
     */
    public AdminRecord setLastname(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.admin.lastname</code>.
     */
    public String getLastname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.admin.type</code>.
     */
    public AdminRecord setType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.admin.type</code>.
     */
    public String getType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.admin.student_id</code>.
     */
    public AdminRecord setStudentId(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.admin.student_id</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.admin.parent_id</code>.
     */
    public AdminRecord setParentId(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.admin.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.admin.professor_id</code>.
     */
    public AdminRecord setProfessorId(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.admin.professor_id</code>.
     */
    public Integer getProfessorId() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, String, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, String, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Admin.ADMIN.ADMIN_ID;
    }

    @Override
    public Field<String> field2() {
        return Admin.ADMIN.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return Admin.ADMIN.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return Admin.ADMIN.FIRSTNAME;
    }

    @Override
    public Field<String> field5() {
        return Admin.ADMIN.LASTNAME;
    }

    @Override
    public Field<String> field6() {
        return Admin.ADMIN.TYPE;
    }

    @Override
    public Field<Integer> field7() {
        return Admin.ADMIN.STUDENT_ID;
    }

    @Override
    public Field<Integer> field8() {
        return Admin.ADMIN.PARENT_ID;
    }

    @Override
    public Field<Integer> field9() {
        return Admin.ADMIN.PROFESSOR_ID;
    }

    @Override
    public Integer component1() {
        return getAdminId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getFirstname();
    }

    @Override
    public String component5() {
        return getLastname();
    }

    @Override
    public String component6() {
        return getType();
    }

    @Override
    public Integer component7() {
        return getStudentId();
    }

    @Override
    public Integer component8() {
        return getParentId();
    }

    @Override
    public Integer component9() {
        return getProfessorId();
    }

    @Override
    public Integer value1() {
        return getAdminId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getFirstname();
    }

    @Override
    public String value5() {
        return getLastname();
    }

    @Override
    public String value6() {
        return getType();
    }

    @Override
    public Integer value7() {
        return getStudentId();
    }

    @Override
    public Integer value8() {
        return getParentId();
    }

    @Override
    public Integer value9() {
        return getProfessorId();
    }

    @Override
    public AdminRecord value1(Integer value) {
        setAdminId(value);
        return this;
    }

    @Override
    public AdminRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public AdminRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AdminRecord value4(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public AdminRecord value5(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public AdminRecord value6(String value) {
        setType(value);
        return this;
    }

    @Override
    public AdminRecord value7(Integer value) {
        setStudentId(value);
        return this;
    }

    @Override
    public AdminRecord value8(Integer value) {
        setParentId(value);
        return this;
    }

    @Override
    public AdminRecord value9(Integer value) {
        setProfessorId(value);
        return this;
    }

    @Override
    public AdminRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminRecord
     */
    public AdminRecord() {
        super(Admin.ADMIN);
    }

    /**
     * Create a detached, initialised AdminRecord
     */
    public AdminRecord(Integer adminId, String username, String password, String firstname, String lastname, String type, Integer studentId, Integer parentId, Integer professorId) {
        super(Admin.ADMIN);

        set(0, adminId);
        set(1, username);
        set(2, password);
        set(3, firstname);
        set(4, lastname);
        set(5, type);
        set(6, studentId);
        set(7, parentId);
        set(8, professorId);
    }
}
