/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.ssglobal.revalida.codes.model.tables.Grades;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GradesRecord extends UpdatableRecordImpl<GradesRecord> implements Record7<Integer, Integer, Integer, String, LocalDate, Boolean, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.grades.grade_id</code>.
     */
    public GradesRecord setGradeId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.grades.grade_id</code>.
     */
    public Integer getGradeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.grades.session_id</code>.
     */
    public GradesRecord setSessionId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.grades.session_id</code>.
     */
    public Integer getSessionId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.grades.grade</code>.
     */
    public GradesRecord setGrade(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.grades.grade</code>.
     */
    public Integer getGrade() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.grades.comment</code>.
     */
    public GradesRecord setComment(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.grades.comment</code>.
     */
    public String getComment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.grades.date_modified</code>.
     */
    public GradesRecord setDateModified(LocalDate value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.grades.date_modified</code>.
     */
    public LocalDate getDateModified() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.grades.remarks</code>.
     */
    public GradesRecord setRemarks(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.grades.remarks</code>.
     */
    public Boolean getRemarks() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.grades.status</code>.
     */
    public GradesRecord setStatus(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.grades.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, String, LocalDate, Boolean, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, String, LocalDate, Boolean, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Grades.GRADES.GRADE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Grades.GRADES.SESSION_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Grades.GRADES.GRADE;
    }

    @Override
    public Field<String> field4() {
        return Grades.GRADES.COMMENT;
    }

    @Override
    public Field<LocalDate> field5() {
        return Grades.GRADES.DATE_MODIFIED;
    }

    @Override
    public Field<Boolean> field6() {
        return Grades.GRADES.REMARKS;
    }

    @Override
    public Field<String> field7() {
        return Grades.GRADES.STATUS;
    }

    @Override
    public Integer component1() {
        return getGradeId();
    }

    @Override
    public Integer component2() {
        return getSessionId();
    }

    @Override
    public Integer component3() {
        return getGrade();
    }

    @Override
    public String component4() {
        return getComment();
    }

    @Override
    public LocalDate component5() {
        return getDateModified();
    }

    @Override
    public Boolean component6() {
        return getRemarks();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getGradeId();
    }

    @Override
    public Integer value2() {
        return getSessionId();
    }

    @Override
    public Integer value3() {
        return getGrade();
    }

    @Override
    public String value4() {
        return getComment();
    }

    @Override
    public LocalDate value5() {
        return getDateModified();
    }

    @Override
    public Boolean value6() {
        return getRemarks();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public GradesRecord value1(Integer value) {
        setGradeId(value);
        return this;
    }

    @Override
    public GradesRecord value2(Integer value) {
        setSessionId(value);
        return this;
    }

    @Override
    public GradesRecord value3(Integer value) {
        setGrade(value);
        return this;
    }

    @Override
    public GradesRecord value4(String value) {
        setComment(value);
        return this;
    }

    @Override
    public GradesRecord value5(LocalDate value) {
        setDateModified(value);
        return this;
    }

    @Override
    public GradesRecord value6(Boolean value) {
        setRemarks(value);
        return this;
    }

    @Override
    public GradesRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public GradesRecord values(Integer value1, Integer value2, Integer value3, String value4, LocalDate value5, Boolean value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GradesRecord
     */
    public GradesRecord() {
        super(Grades.GRADES);
    }

    /**
     * Create a detached, initialised GradesRecord
     */
    public GradesRecord(Integer gradeId, Integer sessionId, Integer grade, String comment, LocalDate dateModified, Boolean remarks, String status) {
        super(Grades.GRADES);

        setGradeId(gradeId);
        setSessionId(sessionId);
        setGrade(grade);
        setComment(comment);
        setDateModified(dateModified);
        setRemarks(remarks);
        setStatus(status);
    }

    /**
     * Create a detached, initialised GradesRecord
     */
    public GradesRecord(org.ssglobal.revalida.codes.model.tables.pojos.Grades value) {
        super(Grades.GRADES);

        if (value != null) {
            setGradeId(value.getGradeId());
            setSessionId(value.getSessionId());
            setGrade(value.getGrade());
            setComment(value.getComment());
            setDateModified(value.getDateModified());
            setRemarks(value.getRemarks());
            setStatus(value.getStatus());
        }
    }
}
