/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.ssglobal.revalida.codes.model.tables.ProfessorLoad;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfessorLoadRecord extends UpdatableRecordImpl<ProfessorLoadRecord> implements Record5<Integer, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -1588785648;

    /**
     * Setter for <code>public.professor_load.load_id</code>.
     */
    public ProfessorLoadRecord setLoadId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.professor_load.load_id</code>.
     */
    public Integer getLoadId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.professor_load.professor_id</code>.
     */
    public ProfessorLoadRecord setProfessorId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.professor_load.professor_id</code>.
     */
    public Integer getProfessorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.professor_load.course_title</code>.
     */
    public ProfessorLoadRecord setCourseTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.professor_load.course_title</code>.
     */
    public String getCourseTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.professor_load.section</code>.
     */
    public ProfessorLoadRecord setSection(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.professor_load.section</code>.
     */
    public Integer getSection() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.professor_load.year_level</code>.
     */
    public ProfessorLoadRecord setYearLevel(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.professor_load.year_level</code>.
     */
    public Integer getYearLevel() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ProfessorLoad.PROFESSOR_LOAD.LOAD_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ProfessorLoad.PROFESSOR_LOAD.PROFESSOR_ID;
    }

    @Override
    public Field<String> field3() {
        return ProfessorLoad.PROFESSOR_LOAD.COURSE_TITLE;
    }

    @Override
    public Field<Integer> field4() {
        return ProfessorLoad.PROFESSOR_LOAD.SECTION;
    }

    @Override
    public Field<Integer> field5() {
        return ProfessorLoad.PROFESSOR_LOAD.YEAR_LEVEL;
    }

    @Override
    public Integer component1() {
        return getLoadId();
    }

    @Override
    public Integer component2() {
        return getProfessorId();
    }

    @Override
    public String component3() {
        return getCourseTitle();
    }

    @Override
    public Integer component4() {
        return getSection();
    }

    @Override
    public Integer component5() {
        return getYearLevel();
    }

    @Override
    public Integer value1() {
        return getLoadId();
    }

    @Override
    public Integer value2() {
        return getProfessorId();
    }

    @Override
    public String value3() {
        return getCourseTitle();
    }

    @Override
    public Integer value4() {
        return getSection();
    }

    @Override
    public Integer value5() {
        return getYearLevel();
    }

    @Override
    public ProfessorLoadRecord value1(Integer value) {
        setLoadId(value);
        return this;
    }

    @Override
    public ProfessorLoadRecord value2(Integer value) {
        setProfessorId(value);
        return this;
    }

    @Override
    public ProfessorLoadRecord value3(String value) {
        setCourseTitle(value);
        return this;
    }

    @Override
    public ProfessorLoadRecord value4(Integer value) {
        setSection(value);
        return this;
    }

    @Override
    public ProfessorLoadRecord value5(Integer value) {
        setYearLevel(value);
        return this;
    }

    @Override
    public ProfessorLoadRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfessorLoadRecord
     */
    public ProfessorLoadRecord() {
        super(ProfessorLoad.PROFESSOR_LOAD);
    }

    /**
     * Create a detached, initialised ProfessorLoadRecord
     */
    public ProfessorLoadRecord(Integer loadId, Integer professorId, String courseTitle, Integer section, Integer yearLevel) {
        super(ProfessorLoad.PROFESSOR_LOAD);

        set(0, loadId);
        set(1, professorId);
        set(2, courseTitle);
        set(3, section);
        set(4, yearLevel);
    }
}
