/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;
import org.ssglobal.revalida.codes.model.tables.Student;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record17<Integer, Integer, Integer, Integer, String, String, String, String, LocalDate, String, Integer, String, String, Boolean, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.student.student_id</code>.
     */
    public StudentRecord setStudentId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.student.student_id</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.student.program_id</code>.
     */
    public StudentRecord setProgramId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.student.program_id</code>.
     */
    public Integer getProgramId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.student.subject_id</code>.
     */
    public StudentRecord setSubjectId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.student.subject_id</code>.
     */
    public Integer getSubjectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.student.grade_id</code>.
     */
    public StudentRecord setGradeId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.student.grade_id</code>.
     */
    public Integer getGradeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.student.password</code>.
     */
    public StudentRecord setPassword(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.student.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.student.firstname</code>.
     */
    public StudentRecord setFirstname(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.student.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.student.middlename</code>.
     */
    public StudentRecord setMiddlename(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.student.middlename</code>.
     */
    public String getMiddlename() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.student.lastname</code>.
     */
    public StudentRecord setLastname(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.student.lastname</code>.
     */
    public String getLastname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.student.birthdate</code>.
     */
    public StudentRecord setBirthdate(LocalDate value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.student.birthdate</code>.
     */
    public LocalDate getBirthdate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>public.student.semester</code>.
     */
    public StudentRecord setSemester(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.student.semester</code>.
     */
    public String getSemester() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.student.year_level</code>.
     */
    public StudentRecord setYearLevel(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.student.year_level</code>.
     */
    public Integer getYearLevel() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.student.academic_year</code>.
     */
    public StudentRecord setAcademicYear(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.student.academic_year</code>.
     */
    public String getAcademicYear() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.student.status</code>.
     */
    public StudentRecord setStatus(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.student.status</code>.
     */
    public String getStatus() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.student.active_deactive</code>.
     */
    public StudentRecord setActiveDeactive(Boolean value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.student.active_deactive</code>.
     */
    public Boolean getActiveDeactive() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.student.course</code>.
     */
    public StudentRecord setCourse(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.student.course</code>.
     */
    public String getCourse() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.student.type</code>.
     */
    public StudentRecord setType(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.student.type</code>.
     */
    public String getType() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.student.student_number</code>.
     */
    public StudentRecord setStudentNumber(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.student.student_number</code>.
     */
    public String getStudentNumber() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Integer, Integer, Integer, Integer, String, String, String, String, LocalDate, String, Integer, String, String, Boolean, String, String, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Integer, Integer, Integer, Integer, String, String, String, String, LocalDate, String, Integer, String, String, Boolean, String, String, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Student.STUDENT.STUDENT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Student.STUDENT.PROGRAM_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Student.STUDENT.SUBJECT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Student.STUDENT.GRADE_ID;
    }

    @Override
    public Field<String> field5() {
        return Student.STUDENT.PASSWORD;
    }

    @Override
    public Field<String> field6() {
        return Student.STUDENT.FIRSTNAME;
    }

    @Override
    public Field<String> field7() {
        return Student.STUDENT.MIDDLENAME;
    }

    @Override
    public Field<String> field8() {
        return Student.STUDENT.LASTNAME;
    }

    @Override
    public Field<LocalDate> field9() {
        return Student.STUDENT.BIRTHDATE;
    }

    @Override
    public Field<String> field10() {
        return Student.STUDENT.SEMESTER;
    }

    @Override
    public Field<Integer> field11() {
        return Student.STUDENT.YEAR_LEVEL;
    }

    @Override
    public Field<String> field12() {
        return Student.STUDENT.ACADEMIC_YEAR;
    }

    @Override
    public Field<String> field13() {
        return Student.STUDENT.STATUS;
    }

    @Override
    public Field<Boolean> field14() {
        return Student.STUDENT.ACTIVE_DEACTIVE;
    }

    @Override
    public Field<String> field15() {
        return Student.STUDENT.COURSE;
    }

    @Override
    public Field<String> field16() {
        return Student.STUDENT.TYPE;
    }

    @Override
    public Field<String> field17() {
        return Student.STUDENT.STUDENT_NUMBER;
    }

    @Override
    public Integer component1() {
        return getStudentId();
    }

    @Override
    public Integer component2() {
        return getProgramId();
    }

    @Override
    public Integer component3() {
        return getSubjectId();
    }

    @Override
    public Integer component4() {
        return getGradeId();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public String component6() {
        return getFirstname();
    }

    @Override
    public String component7() {
        return getMiddlename();
    }

    @Override
    public String component8() {
        return getLastname();
    }

    @Override
    public LocalDate component9() {
        return getBirthdate();
    }

    @Override
    public String component10() {
        return getSemester();
    }

    @Override
    public Integer component11() {
        return getYearLevel();
    }

    @Override
    public String component12() {
        return getAcademicYear();
    }

    @Override
    public String component13() {
        return getStatus();
    }

    @Override
    public Boolean component14() {
        return getActiveDeactive();
    }

    @Override
    public String component15() {
        return getCourse();
    }

    @Override
    public String component16() {
        return getType();
    }

    @Override
    public String component17() {
        return getStudentNumber();
    }

    @Override
    public Integer value1() {
        return getStudentId();
    }

    @Override
    public Integer value2() {
        return getProgramId();
    }

    @Override
    public Integer value3() {
        return getSubjectId();
    }

    @Override
    public Integer value4() {
        return getGradeId();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public String value6() {
        return getFirstname();
    }

    @Override
    public String value7() {
        return getMiddlename();
    }

    @Override
    public String value8() {
        return getLastname();
    }

    @Override
    public LocalDate value9() {
        return getBirthdate();
    }

    @Override
    public String value10() {
        return getSemester();
    }

    @Override
    public Integer value11() {
        return getYearLevel();
    }

    @Override
    public String value12() {
        return getAcademicYear();
    }

    @Override
    public String value13() {
        return getStatus();
    }

    @Override
    public Boolean value14() {
        return getActiveDeactive();
    }

    @Override
    public String value15() {
        return getCourse();
    }

    @Override
    public String value16() {
        return getType();
    }

    @Override
    public String value17() {
        return getStudentNumber();
    }

    @Override
    public StudentRecord value1(Integer value) {
        setStudentId(value);
        return this;
    }

    @Override
    public StudentRecord value2(Integer value) {
        setProgramId(value);
        return this;
    }

    @Override
    public StudentRecord value3(Integer value) {
        setSubjectId(value);
        return this;
    }

    @Override
    public StudentRecord value4(Integer value) {
        setGradeId(value);
        return this;
    }

    @Override
    public StudentRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public StudentRecord value6(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public StudentRecord value7(String value) {
        setMiddlename(value);
        return this;
    }

    @Override
    public StudentRecord value8(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public StudentRecord value9(LocalDate value) {
        setBirthdate(value);
        return this;
    }

    @Override
    public StudentRecord value10(String value) {
        setSemester(value);
        return this;
    }

    @Override
    public StudentRecord value11(Integer value) {
        setYearLevel(value);
        return this;
    }

    @Override
    public StudentRecord value12(String value) {
        setAcademicYear(value);
        return this;
    }

    @Override
    public StudentRecord value13(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public StudentRecord value14(Boolean value) {
        setActiveDeactive(value);
        return this;
    }

    @Override
    public StudentRecord value15(String value) {
        setCourse(value);
        return this;
    }

    @Override
    public StudentRecord value16(String value) {
        setType(value);
        return this;
    }

    @Override
    public StudentRecord value17(String value) {
        setStudentNumber(value);
        return this;
    }

    @Override
    public StudentRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, LocalDate value9, String value10, Integer value11, String value12, String value13, Boolean value14, String value15, String value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Integer studentId, Integer programId, Integer subjectId, Integer gradeId, String password, String firstname, String middlename, String lastname, LocalDate birthdate, String semester, Integer yearLevel, String academicYear, String status, Boolean activeDeactive, String course, String type, String studentNumber) {
        super(Student.STUDENT);

        setStudentId(studentId);
        setProgramId(programId);
        setSubjectId(subjectId);
        setGradeId(gradeId);
        setPassword(password);
        setFirstname(firstname);
        setMiddlename(middlename);
        setLastname(lastname);
        setBirthdate(birthdate);
        setSemester(semester);
        setYearLevel(yearLevel);
        setAcademicYear(academicYear);
        setStatus(status);
        setActiveDeactive(activeDeactive);
        setCourse(course);
        setType(type);
        setStudentNumber(studentNumber);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(org.ssglobal.revalida.codes.model.tables.pojos.Student value) {
        super(Student.STUDENT);

        if (value != null) {
            setStudentId(value.getStudentId());
            setProgramId(value.getProgramId());
            setSubjectId(value.getSubjectId());
            setGradeId(value.getGradeId());
            setPassword(value.getPassword());
            setFirstname(value.getFirstname());
            setMiddlename(value.getMiddlename());
            setLastname(value.getLastname());
            setBirthdate(value.getBirthdate());
            setSemester(value.getSemester());
            setYearLevel(value.getYearLevel());
            setAcademicYear(value.getAcademicYear());
            setStatus(value.getStatus());
            setActiveDeactive(value.getActiveDeactive());
            setCourse(value.getCourse());
            setType(value.getType());
            setStudentNumber(value.getStudentNumber());
        }
    }
}
