/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.ssglobal.revalida.codes.model.tables.SubjectDetailHistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectDetailHistoryRecord extends UpdatableRecordImpl<SubjectDetailHistoryRecord> implements Record10<Integer, Integer, Integer, Integer, String, LocalDate, String, Integer, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.subject_detail_history.session_id</code>.
     */
    public SubjectDetailHistoryRecord setSessionId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.session_id</code>.
     */
    public Integer getSessionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.subject_detail_history.professor_id</code>.
     */
    public SubjectDetailHistoryRecord setProfessorId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.professor_id</code>.
     */
    public Integer getProfessorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.subject_detail_history.subject_id</code>.
     */
    public SubjectDetailHistoryRecord setSubjectId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.subject_id</code>.
     */
    public Integer getSubjectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.subject_detail_history.academic_year</code>.
     */
    public SubjectDetailHistoryRecord setAcademicYear(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.academic_year</code>.
     */
    public Integer getAcademicYear() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.subject_detail_history.semester</code>.
     */
    public SubjectDetailHistoryRecord setSemester(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.semester</code>.
     */
    public String getSemester() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.subject_detail_history.schedule</code>.
     */
    public SubjectDetailHistoryRecord setSchedule(LocalDate value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.schedule</code>.
     */
    public LocalDate getSchedule() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.subject_detail_history.section</code>.
     */
    public SubjectDetailHistoryRecord setSection(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.section</code>.
     */
    public String getSection() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.subject_detail_history.year_level</code>.
     */
    public SubjectDetailHistoryRecord setYearLevel(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.year_level</code>.
     */
    public Integer getYearLevel() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.subject_detail_history.status</code>.
     */
    public SubjectDetailHistoryRecord setStatus(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.status</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.subject_detail_history.active_deactive</code>.
     */
    public SubjectDetailHistoryRecord setActiveDeactive(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.active_deactive</code>.
     */
    public Boolean getActiveDeactive() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Integer, Integer, String, LocalDate, String, Integer, String, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, Integer, Integer, String, LocalDate, String, Integer, String, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.SESSION_ID;
    }

    @Override
    public Field<Integer> field2() {
        return SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.PROFESSOR_ID;
    }

    @Override
    public Field<Integer> field3() {
        return SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.SUBJECT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.ACADEMIC_YEAR;
    }

    @Override
    public Field<String> field5() {
        return SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.SEMESTER;
    }

    @Override
    public Field<LocalDate> field6() {
        return SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.SCHEDULE;
    }

    @Override
    public Field<String> field7() {
        return SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.SECTION;
    }

    @Override
    public Field<Integer> field8() {
        return SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.YEAR_LEVEL;
    }

    @Override
    public Field<String> field9() {
        return SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.STATUS;
    }

    @Override
    public Field<Boolean> field10() {
        return SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.ACTIVE_DEACTIVE;
    }

    @Override
    public Integer component1() {
        return getSessionId();
    }

    @Override
    public Integer component2() {
        return getProfessorId();
    }

    @Override
    public Integer component3() {
        return getSubjectId();
    }

    @Override
    public Integer component4() {
        return getAcademicYear();
    }

    @Override
    public String component5() {
        return getSemester();
    }

    @Override
    public LocalDate component6() {
        return getSchedule();
    }

    @Override
    public String component7() {
        return getSection();
    }

    @Override
    public Integer component8() {
        return getYearLevel();
    }

    @Override
    public String component9() {
        return getStatus();
    }

    @Override
    public Boolean component10() {
        return getActiveDeactive();
    }

    @Override
    public Integer value1() {
        return getSessionId();
    }

    @Override
    public Integer value2() {
        return getProfessorId();
    }

    @Override
    public Integer value3() {
        return getSubjectId();
    }

    @Override
    public Integer value4() {
        return getAcademicYear();
    }

    @Override
    public String value5() {
        return getSemester();
    }

    @Override
    public LocalDate value6() {
        return getSchedule();
    }

    @Override
    public String value7() {
        return getSection();
    }

    @Override
    public Integer value8() {
        return getYearLevel();
    }

    @Override
    public String value9() {
        return getStatus();
    }

    @Override
    public Boolean value10() {
        return getActiveDeactive();
    }

    @Override
    public SubjectDetailHistoryRecord value1(Integer value) {
        setSessionId(value);
        return this;
    }

    @Override
    public SubjectDetailHistoryRecord value2(Integer value) {
        setProfessorId(value);
        return this;
    }

    @Override
    public SubjectDetailHistoryRecord value3(Integer value) {
        setSubjectId(value);
        return this;
    }

    @Override
    public SubjectDetailHistoryRecord value4(Integer value) {
        setAcademicYear(value);
        return this;
    }

    @Override
    public SubjectDetailHistoryRecord value5(String value) {
        setSemester(value);
        return this;
    }

    @Override
    public SubjectDetailHistoryRecord value6(LocalDate value) {
        setSchedule(value);
        return this;
    }

    @Override
    public SubjectDetailHistoryRecord value7(String value) {
        setSection(value);
        return this;
    }

    @Override
    public SubjectDetailHistoryRecord value8(Integer value) {
        setYearLevel(value);
        return this;
    }

    @Override
    public SubjectDetailHistoryRecord value9(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public SubjectDetailHistoryRecord value10(Boolean value) {
        setActiveDeactive(value);
        return this;
    }

    @Override
    public SubjectDetailHistoryRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, LocalDate value6, String value7, Integer value8, String value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectDetailHistoryRecord
     */
    public SubjectDetailHistoryRecord() {
        super(SubjectDetailHistory.SUBJECT_DETAIL_HISTORY);
    }

    /**
     * Create a detached, initialised SubjectDetailHistoryRecord
     */
    public SubjectDetailHistoryRecord(Integer sessionId, Integer professorId, Integer subjectId, Integer academicYear, String semester, LocalDate schedule, String section, Integer yearLevel, String status, Boolean activeDeactive) {
        super(SubjectDetailHistory.SUBJECT_DETAIL_HISTORY);

        setSessionId(sessionId);
        setProfessorId(professorId);
        setSubjectId(subjectId);
        setAcademicYear(academicYear);
        setSemester(semester);
        setSchedule(schedule);
        setSection(section);
        setYearLevel(yearLevel);
        setStatus(status);
        setActiveDeactive(activeDeactive);
    }

    /**
     * Create a detached, initialised SubjectDetailHistoryRecord
     */
    public SubjectDetailHistoryRecord(org.ssglobal.revalida.codes.model.tables.pojos.SubjectDetailHistory value) {
        super(SubjectDetailHistory.SUBJECT_DETAIL_HISTORY);

        if (value != null) {
            setSessionId(value.getSessionId());
            setProfessorId(value.getProfessorId());
            setSubjectId(value.getSubjectId());
            setAcademicYear(value.getAcademicYear());
            setSemester(value.getSemester());
            setSchedule(value.getSchedule());
            setSection(value.getSection());
            setYearLevel(value.getYearLevel());
            setStatus(value.getStatus());
            setActiveDeactive(value.getActiveDeactive());
        }
    }
}
