/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.ssglobal.revalida.codes.model.tables.AdminUser;
import org.ssglobal.revalida.codes.model.tables.Grades;
import org.ssglobal.revalida.codes.model.tables.Professor;
import org.ssglobal.revalida.codes.model.tables.ProfessorLoad;
import org.ssglobal.revalida.codes.model.tables.Student;
import org.ssglobal.revalida.codes.model.tables.Subject;
import org.ssglobal.revalida.codes.model.tables.SubjectDetailHistory;
import org.ssglobal.revalida.codes.model.tables.records.AdminUserRecord;
import org.ssglobal.revalida.codes.model.tables.records.GradesRecord;
import org.ssglobal.revalida.codes.model.tables.records.ProfessorLoadRecord;
import org.ssglobal.revalida.codes.model.tables.records.ProfessorRecord;
import org.ssglobal.revalida.codes.model.tables.records.StudentRecord;
import org.ssglobal.revalida.codes.model.tables.records.SubjectDetailHistoryRecord;
import org.ssglobal.revalida.codes.model.tables.records.SubjectRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdminUserRecord> ADMIN_USER_PKEY = Internal.createUniqueKey(AdminUser.ADMIN_USER, DSL.name("admin_user_pkey"), new TableField[] { AdminUser.ADMIN_USER.ADMIN_ID }, true);
    public static final UniqueKey<GradesRecord> GRADES_PKEY = Internal.createUniqueKey(Grades.GRADES, DSL.name("grades_pkey"), new TableField[] { Grades.GRADES.GRADE_ID }, true);
    public static final UniqueKey<ProfessorRecord> PROFESSOR_PKEY = Internal.createUniqueKey(Professor.PROFESSOR, DSL.name("professor_pkey"), new TableField[] { Professor.PROFESSOR.PROFESSOR_ID }, true);
    public static final UniqueKey<ProfessorLoadRecord> PROFESSOR_LOAD_PKEY = Internal.createUniqueKey(ProfessorLoad.PROFESSOR_LOAD, DSL.name("professor_load_pkey"), new TableField[] { ProfessorLoad.PROFESSOR_LOAD.LOAD_ID }, true);
    public static final UniqueKey<StudentRecord> STUDENT_PKEY = Internal.createUniqueKey(Student.STUDENT, DSL.name("student_pkey"), new TableField[] { Student.STUDENT.STUDENT_ID }, true);
    public static final UniqueKey<SubjectRecord> SUBJECT_PKEY = Internal.createUniqueKey(Subject.SUBJECT, DSL.name("subject_pkey"), new TableField[] { Subject.SUBJECT.SUBJECT_ID }, true);
    public static final UniqueKey<SubjectDetailHistoryRecord> SUBJECT_DETAIL_HISTORY_PKEY = Internal.createUniqueKey(SubjectDetailHistory.SUBJECT_DETAIL_HISTORY, DSL.name("subject_detail_history_pkey"), new TableField[] { SubjectDetailHistory.SUBJECT_DETAIL_HISTORY.SESSION_ID }, true);
}
