/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.ssglobal.revalida.codes.model.tables.AdminUser;
import org.ssglobal.revalida.codes.model.tables.Grades;
import org.ssglobal.revalida.codes.model.tables.Professor;
import org.ssglobal.revalida.codes.model.tables.ProfessorLoad;
import org.ssglobal.revalida.codes.model.tables.Student;
import org.ssglobal.revalida.codes.model.tables.Subject;
import org.ssglobal.revalida.codes.model.tables.SubjectDetailHistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.admin_user</code>.
     */
    public final AdminUser ADMIN_USER = AdminUser.ADMIN_USER;

    /**
     * The table <code>public.grades</code>.
     */
    public final Grades GRADES = Grades.GRADES;

    /**
     * The table <code>public.professor</code>.
     */
    public final Professor PROFESSOR = Professor.PROFESSOR;

    /**
     * The table <code>public.professor_load</code>.
     */
    public final ProfessorLoad PROFESSOR_LOAD = ProfessorLoad.PROFESSOR_LOAD;

    /**
     * The table <code>public.student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.subject</code>.
     */
    public final Subject SUBJECT = Subject.SUBJECT;

    /**
     * The table <code>public.subject_detail_history</code>.
     */
    public final SubjectDetailHistory SUBJECT_DETAIL_HISTORY = SubjectDetailHistory.SUBJECT_DETAIL_HISTORY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AdminUser.ADMIN_USER,
            Grades.GRADES,
            Professor.PROFESSOR,
            ProfessorLoad.PROFESSOR_LOAD,
            Student.STUDENT,
            Subject.SUBJECT,
            SubjectDetailHistory.SUBJECT_DETAIL_HISTORY
        );
    }
}
