/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.ssglobal.revalida.codes.model.tables.Admin;
import org.ssglobal.revalida.codes.model.tables.Grades;
import org.ssglobal.revalida.codes.model.tables.Parent;
import org.ssglobal.revalida.codes.model.tables.Professor;
import org.ssglobal.revalida.codes.model.tables.ProfessorLoad;
import org.ssglobal.revalida.codes.model.tables.Program;
import org.ssglobal.revalida.codes.model.tables.Student;
import org.ssglobal.revalida.codes.model.tables.Subject;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 514698499;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.admin</code>.
     */
    public final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>public.grades</code>.
     */
    public final Grades GRADES = Grades.GRADES;

    /**
     * The table <code>public.parent</code>.
     */
    public final Parent PARENT = Parent.PARENT;

    /**
     * The table <code>public.professor</code>.
     */
    public final Professor PROFESSOR = Professor.PROFESSOR;

    /**
     * The table <code>public.professor_load</code>.
     */
    public final ProfessorLoad PROFESSOR_LOAD = ProfessorLoad.PROFESSOR_LOAD;

    /**
     * The table <code>public.program</code>.
     */
    public final Program PROGRAM = Program.PROGRAM;

    /**
     * The table <code>public.student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.subject</code>.
     */
    public final Subject SUBJECT = Subject.SUBJECT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Admin.ADMIN,
            Grades.GRADES,
            Parent.PARENT,
            Professor.PROFESSOR,
            ProfessorLoad.PROFESSOR_LOAD,
            Program.PROGRAM,
            Student.STUDENT,
            Subject.SUBJECT);
    }
}
