/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model;


import org.ssglobal.revalida.codes.model.tables.Admin;
import org.ssglobal.revalida.codes.model.tables.Grades;
import org.ssglobal.revalida.codes.model.tables.Parent;
import org.ssglobal.revalida.codes.model.tables.Professor;
import org.ssglobal.revalida.codes.model.tables.ProfessorLoad;
import org.ssglobal.revalida.codes.model.tables.Program;
import org.ssglobal.revalida.codes.model.tables.Student;
import org.ssglobal.revalida.codes.model.tables.Subject;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.admin</code>.
     */
    public static final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>public.grades</code>.
     */
    public static final Grades GRADES = Grades.GRADES;

    /**
     * The table <code>public.parent</code>.
     */
    public static final Parent PARENT = Parent.PARENT;

    /**
     * The table <code>public.professor</code>.
     */
    public static final Professor PROFESSOR = Professor.PROFESSOR;

    /**
     * The table <code>public.professor_load</code>.
     */
    public static final ProfessorLoad PROFESSOR_LOAD = ProfessorLoad.PROFESSOR_LOAD;

    /**
     * The table <code>public.program</code>.
     */
    public static final Program PROGRAM = Program.PROGRAM;

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.subject</code>.
     */
    public static final Subject SUBJECT = Subject.SUBJECT;
}
