/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model;


import org.ssglobal.revalida.codes.model.tables.AdminUser;
import org.ssglobal.revalida.codes.model.tables.Grades;
import org.ssglobal.revalida.codes.model.tables.Professor;
import org.ssglobal.revalida.codes.model.tables.ProfessorLoad;
import org.ssglobal.revalida.codes.model.tables.Student;
import org.ssglobal.revalida.codes.model.tables.Subject;
import org.ssglobal.revalida.codes.model.tables.SubjectDetailHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.admin_user</code>.
     */
    public static final AdminUser ADMIN_USER = AdminUser.ADMIN_USER;

    /**
     * The table <code>public.grades</code>.
     */
    public static final Grades GRADES = Grades.GRADES;

    /**
     * The table <code>public.professor</code>.
     */
    public static final Professor PROFESSOR = Professor.PROFESSOR;

    /**
     * The table <code>public.professor_load</code>.
     */
    public static final ProfessorLoad PROFESSOR_LOAD = ProfessorLoad.PROFESSOR_LOAD;

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.subject</code>.
     */
    public static final Subject SUBJECT = Subject.SUBJECT;

    /**
     * The table <code>public.subject_detail_history</code>.
     */
    public static final SubjectDetailHistory SUBJECT_DETAIL_HISTORY = SubjectDetailHistory.SUBJECT_DETAIL_HISTORY;
}
