/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables;


import java.time.LocalDate;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.ssglobal.revalida.codes.model.Keys;
import org.ssglobal.revalida.codes.model.Public;
import org.ssglobal.revalida.codes.model.tables.records.GradesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Grades extends TableImpl<GradesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.grades</code>
     */
    public static final Grades GRADES = new Grades();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GradesRecord> getRecordType() {
        return GradesRecord.class;
    }

    /**
     * The column <code>public.grades.grade_id</code>.
     */
    public final TableField<GradesRecord, Integer> GRADE_ID = createField(DSL.name("grade_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.grades.session_id</code>.
     */
    public final TableField<GradesRecord, Integer> SESSION_ID = createField(DSL.name("session_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.grades.grade</code>.
     */
    public final TableField<GradesRecord, Integer> GRADE = createField(DSL.name("grade"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.grades.comment</code>.
     */
    public final TableField<GradesRecord, String> COMMENT = createField(DSL.name("comment"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.grades.date_modified</code>.
     */
    public final TableField<GradesRecord, LocalDate> DATE_MODIFIED = createField(DSL.name("date_modified"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.grades.remarks</code>.
     */
    public final TableField<GradesRecord, Boolean> REMARKS = createField(DSL.name("remarks"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.grades.status</code>.
     */
    public final TableField<GradesRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false), this, "");

    private Grades(Name alias, Table<GradesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Grades(Name alias, Table<GradesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.grades</code> table reference
     */
    public Grades(String alias) {
        this(DSL.name(alias), GRADES);
    }

    /**
     * Create an aliased <code>public.grades</code> table reference
     */
    public Grades(Name alias) {
        this(alias, GRADES);
    }

    /**
     * Create a <code>public.grades</code> table reference
     */
    public Grades() {
        this(DSL.name("grades"), null);
    }

    public <O extends Record> Grades(Table<O> child, ForeignKey<O, GradesRecord> key) {
        super(child, key, GRADES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<GradesRecord> getPrimaryKey() {
        return Keys.GRADES_PKEY;
    }

    @Override
    public Grades as(String alias) {
        return new Grades(DSL.name(alias), this);
    }

    @Override
    public Grades as(Name alias) {
        return new Grades(alias, this);
    }

    @Override
    public Grades as(Table<?> alias) {
        return new Grades(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Grades rename(String name) {
        return new Grades(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Grades rename(Name name) {
        return new Grades(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Grades rename(Table<?> name) {
        return new Grades(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, String, LocalDate, Boolean, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Integer, ? super Integer, ? super Integer, ? super String, ? super LocalDate, ? super Boolean, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Integer, ? super Integer, ? super Integer, ? super String, ? super LocalDate, ? super Boolean, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
