/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.ssglobal.revalida.codes.model.Keys;
import org.ssglobal.revalida.codes.model.Public;
import org.ssglobal.revalida.codes.model.tables.records.ProfessorRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Professor extends TableImpl<ProfessorRecord> {

    private static final long serialVersionUID = -782811845;

    /**
     * The reference instance of <code>public.professor</code>
     */
    public static final Professor PROFESSOR = new Professor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfessorRecord> getRecordType() {
        return ProfessorRecord.class;
    }

    /**
     * The column <code>public.professor.professor_id</code>.
     */
    public final TableField<ProfessorRecord, Integer> PROFESSOR_ID = createField(DSL.name("professor_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.professor.student_id</code>.
     */
    public final TableField<ProfessorRecord, Integer> STUDENT_ID = createField(DSL.name("student_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.professor.grade_id</code>.
     */
    public final TableField<ProfessorRecord, Integer> GRADE_ID = createField(DSL.name("grade_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.professor.professor_number</code>.
     */
    public final TableField<ProfessorRecord, String> PROFESSOR_NUMBER = createField(DSL.name("professor_number"), org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.professor.professor_name</code>.
     */
    public final TableField<ProfessorRecord, String> PROFESSOR_NAME = createField(DSL.name("professor_name"), org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.professor.gender</code>.
     */
    public final TableField<ProfessorRecord, String> GENDER = createField(DSL.name("gender"), org.jooq.impl.SQLDataType.VARCHAR(6).nullable(false), this, "");

    /**
     * The column <code>public.professor.status</code>.
     */
    public final TableField<ProfessorRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.professor.birthdate</code>.
     */
    public final TableField<ProfessorRecord, LocalDate> BIRTHDATE = createField(DSL.name("birthdate"), org.jooq.impl.SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.professor.password</code>.
     */
    public final TableField<ProfessorRecord, String> PASSWORD = createField(DSL.name("password"), org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.professor.active_deactive</code>.
     */
    public final TableField<ProfessorRecord, Boolean> ACTIVE_DEACTIVE = createField(DSL.name("active_deactive"), org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.professor.type</code>.
     */
    public final TableField<ProfessorRecord, String> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * Create a <code>public.professor</code> table reference
     */
    public Professor() {
        this(DSL.name("professor"), null);
    }

    /**
     * Create an aliased <code>public.professor</code> table reference
     */
    public Professor(String alias) {
        this(DSL.name(alias), PROFESSOR);
    }

    /**
     * Create an aliased <code>public.professor</code> table reference
     */
    public Professor(Name alias) {
        this(alias, PROFESSOR);
    }

    private Professor(Name alias, Table<ProfessorRecord> aliased) {
        this(alias, aliased, null);
    }

    private Professor(Name alias, Table<ProfessorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Professor(Table<O> child, ForeignKey<O, ProfessorRecord> key) {
        super(child, key, PROFESSOR);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<ProfessorRecord> getPrimaryKey() {
        return Keys.PROFESSOR_PKEY;
    }

    @Override
    public List<UniqueKey<ProfessorRecord>> getKeys() {
        return Arrays.<UniqueKey<ProfessorRecord>>asList(Keys.PROFESSOR_PKEY);
    }

    @Override
    public List<ForeignKey<ProfessorRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProfessorRecord, ?>>asList(Keys.PROFESSOR__PROFESSOR_STUDENT_ID_FKEY, Keys.PROFESSOR__PROFESSOR_GRADE_ID_FKEY);
    }

    public Student student() {
        return new Student(this, Keys.PROFESSOR__PROFESSOR_STUDENT_ID_FKEY);
    }

    public Grades grades() {
        return new Grades(this, Keys.PROFESSOR__PROFESSOR_GRADE_ID_FKEY);
    }

    @Override
    public Professor as(String alias) {
        return new Professor(DSL.name(alias), this);
    }

    @Override
    public Professor as(Name alias) {
        return new Professor(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Professor rename(String name) {
        return new Professor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Professor rename(Name name) {
        return new Professor(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Integer, Integer, String, String, String, String, LocalDate, String, Boolean, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
