/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables;


import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.ssglobal.revalida.codes.model.Keys;
import org.ssglobal.revalida.codes.model.Public;
import org.ssglobal.revalida.codes.model.tables.records.SubjectRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subject extends TableImpl<SubjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.subject</code>
     */
    public static final Subject SUBJECT = new Subject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubjectRecord> getRecordType() {
        return SubjectRecord.class;
    }

    /**
     * The column <code>public.subject.subject_id</code>.
     */
    public final TableField<SubjectRecord, Integer> SUBJECT_ID = createField(DSL.name("subject_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.subject.subject_code</code>.
     */
    public final TableField<SubjectRecord, String> SUBJECT_CODE = createField(DSL.name("subject_code"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.subject.subject_title</code>.
     */
    public final TableField<SubjectRecord, String> SUBJECT_TITLE = createField(DSL.name("subject_title"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.subject.unit</code>.
     */
    public final TableField<SubjectRecord, Integer> UNIT = createField(DSL.name("unit"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.subject.active_deactive</code>.
     */
    public final TableField<SubjectRecord, Boolean> ACTIVE_DEACTIVE = createField(DSL.name("active_deactive"), SQLDataType.BOOLEAN, this, "");

    private Subject(Name alias, Table<SubjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private Subject(Name alias, Table<SubjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.subject</code> table reference
     */
    public Subject(String alias) {
        this(DSL.name(alias), SUBJECT);
    }

    /**
     * Create an aliased <code>public.subject</code> table reference
     */
    public Subject(Name alias) {
        this(alias, SUBJECT);
    }

    /**
     * Create a <code>public.subject</code> table reference
     */
    public Subject() {
        this(DSL.name("subject"), null);
    }

    public <O extends Record> Subject(Table<O> child, ForeignKey<O, SubjectRecord> key) {
        super(child, key, SUBJECT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SubjectRecord> getPrimaryKey() {
        return Keys.SUBJECT_PKEY;
    }

    @Override
    public Subject as(String alias) {
        return new Subject(DSL.name(alias), this);
    }

    @Override
    public Subject as(Name alias) {
        return new Subject(alias, this);
    }

    @Override
    public Subject as(Table<?> alias) {
        return new Subject(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Subject rename(String name) {
        return new Subject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Subject rename(Name name) {
        return new Subject(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Subject rename(Table<?> name) {
        return new Subject(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super String, ? super String, ? super Integer, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super String, ? super String, ? super Integer, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
