/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Admin implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer adminId;
    private String username;
    private String password;
    private String firstname;
    private String lastname;
    private String type;
    private Integer studentId;
    private Integer parentId;
    private Integer professorId;

    public Admin() {}

    public Admin(Admin value) {
        this.adminId = value.adminId;
        this.username = value.username;
        this.password = value.password;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.type = value.type;
        this.studentId = value.studentId;
        this.parentId = value.parentId;
        this.professorId = value.professorId;
    }

    public Admin(
        Integer adminId,
        String username,
        String password,
        String firstname,
        String lastname,
        String type,
        Integer studentId,
        Integer parentId,
        Integer professorId
    ) {
        this.adminId = adminId;
        this.username = username;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
        this.type = type;
        this.studentId = studentId;
        this.parentId = parentId;
        this.professorId = professorId;
    }

    /**
     * Getter for <code>public.admin.admin_id</code>.
     */
    public Integer getAdminId() {
        return this.adminId;
    }

    /**
     * Setter for <code>public.admin.admin_id</code>.
     */
    public Admin setAdminId(Integer adminId) {
        this.adminId = adminId;
        return this;
    }

    /**
     * Getter for <code>public.admin.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.admin.username</code>.
     */
    public Admin setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>public.admin.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.admin.password</code>.
     */
    public Admin setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.admin.firstname</code>.
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Setter for <code>public.admin.firstname</code>.
     */
    public Admin setFirstname(String firstname) {
        this.firstname = firstname;
        return this;
    }

    /**
     * Getter for <code>public.admin.lastname</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>public.admin.lastname</code>.
     */
    public Admin setLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }

    /**
     * Getter for <code>public.admin.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.admin.type</code>.
     */
    public Admin setType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for <code>public.admin.student_id</code>.
     */
    public Integer getStudentId() {
        return this.studentId;
    }

    /**
     * Setter for <code>public.admin.student_id</code>.
     */
    public Admin setStudentId(Integer studentId) {
        this.studentId = studentId;
        return this;
    }

    /**
     * Getter for <code>public.admin.parent_id</code>.
     */
    public Integer getParentId() {
        return this.parentId;
    }

    /**
     * Setter for <code>public.admin.parent_id</code>.
     */
    public Admin setParentId(Integer parentId) {
        this.parentId = parentId;
        return this;
    }

    /**
     * Getter for <code>public.admin.professor_id</code>.
     */
    public Integer getProfessorId() {
        return this.professorId;
    }

    /**
     * Setter for <code>public.admin.professor_id</code>.
     */
    public Admin setProfessorId(Integer professorId) {
        this.professorId = professorId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Admin other = (Admin) obj;
        if (this.adminId == null) {
            if (other.adminId != null)
                return false;
        }
        else if (!this.adminId.equals(other.adminId))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.firstname == null) {
            if (other.firstname != null)
                return false;
        }
        else if (!this.firstname.equals(other.firstname))
            return false;
        if (this.lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!this.lastname.equals(other.lastname))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.studentId == null) {
            if (other.studentId != null)
                return false;
        }
        else if (!this.studentId.equals(other.studentId))
            return false;
        if (this.parentId == null) {
            if (other.parentId != null)
                return false;
        }
        else if (!this.parentId.equals(other.parentId))
            return false;
        if (this.professorId == null) {
            if (other.professorId != null)
                return false;
        }
        else if (!this.professorId.equals(other.professorId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.adminId == null) ? 0 : this.adminId.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.firstname == null) ? 0 : this.firstname.hashCode());
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.studentId == null) ? 0 : this.studentId.hashCode());
        result = prime * result + ((this.parentId == null) ? 0 : this.parentId.hashCode());
        result = prime * result + ((this.professorId == null) ? 0 : this.professorId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Admin (");

        sb.append(adminId);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(type);
        sb.append(", ").append(studentId);
        sb.append(", ").append(parentId);
        sb.append(", ").append(professorId);

        sb.append(")");
        return sb.toString();
    }
}
