/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Admin implements Serializable {

    private static final long serialVersionUID = -568649105;

    private Integer adminId;
    private String  username;
    private String  password;
    private String  firstname;
    private String  lastname;
    private String  type;

    public Admin() {}

    public Admin(Admin value) {
        this.adminId = value.adminId;
        this.username = value.username;
        this.password = value.password;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.type = value.type;
    }

    public Admin(
        Integer adminId,
        String  username,
        String  password,
        String  firstname,
        String  lastname,
        String  type
    ) {
        this.adminId = adminId;
        this.username = username;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
        this.type = type;
    }

    public Integer getAdminId() {
        return this.adminId;
    }

    public Admin setAdminId(Integer adminId) {
        this.adminId = adminId;
        return this;
    }

    public String getUsername() {
        return this.username;
    }

    public Admin setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public Admin setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public Admin setFirstname(String firstname) {
        this.firstname = firstname;
        return this;
    }

    public String getLastname() {
        return this.lastname;
    }

    public Admin setLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }

    public String getType() {
        return this.type;
    }

    public Admin setType(String type) {
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Admin other = (Admin) obj;
        if (adminId == null) {
            if (other.adminId != null)
                return false;
        }
        else if (!adminId.equals(other.adminId))
            return false;
        if (username == null) {
            if (other.username != null)
                return false;
        }
        else if (!username.equals(other.username))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        if (firstname == null) {
            if (other.firstname != null)
                return false;
        }
        else if (!firstname.equals(other.firstname))
            return false;
        if (lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!lastname.equals(other.lastname))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.adminId == null) ? 0 : this.adminId.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.firstname == null) ? 0 : this.firstname.hashCode());
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Admin (");

        sb.append(adminId);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
