/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private String lastname;
    private String firstname;
    private Integer adminId;
    private String username;
    private String password;
    private String type;

    public AdminUser() {}

    public AdminUser(AdminUser value) {
        this.lastname = value.lastname;
        this.firstname = value.firstname;
        this.adminId = value.adminId;
        this.username = value.username;
        this.password = value.password;
        this.type = value.type;
    }

    public AdminUser(
        String lastname,
        String firstname,
        Integer adminId,
        String username,
        String password,
        String type
    ) {
        this.lastname = lastname;
        this.firstname = firstname;
        this.adminId = adminId;
        this.username = username;
        this.password = password;
        this.type = type;
    }

    /**
     * Getter for <code>public.admin_user.lastname</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>public.admin_user.lastname</code>.
     */
    public AdminUser setLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }

    /**
     * Getter for <code>public.admin_user.firstname</code>.
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Setter for <code>public.admin_user.firstname</code>.
     */
    public AdminUser setFirstname(String firstname) {
        this.firstname = firstname;
        return this;
    }

    /**
     * Getter for <code>public.admin_user.admin_id</code>.
     */
    public Integer getAdminId() {
        return this.adminId;
    }

    /**
     * Setter for <code>public.admin_user.admin_id</code>.
     */
    public AdminUser setAdminId(Integer adminId) {
        this.adminId = adminId;
        return this;
    }

    /**
     * Getter for <code>public.admin_user.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.admin_user.username</code>.
     */
    public AdminUser setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>public.admin_user.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.admin_user.password</code>.
     */
    public AdminUser setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.admin_user.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.admin_user.type</code>.
     */
    public AdminUser setType(String type) {
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AdminUser other = (AdminUser) obj;
        if (this.lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!this.lastname.equals(other.lastname))
            return false;
        if (this.firstname == null) {
            if (other.firstname != null)
                return false;
        }
        else if (!this.firstname.equals(other.firstname))
            return false;
        if (this.adminId == null) {
            if (other.adminId != null)
                return false;
        }
        else if (!this.adminId.equals(other.adminId))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        result = prime * result + ((this.firstname == null) ? 0 : this.firstname.hashCode());
        result = prime * result + ((this.adminId == null) ? 0 : this.adminId.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AdminUser (");

        sb.append(lastname);
        sb.append(", ").append(firstname);
        sb.append(", ").append(adminId);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
