/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Grades implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer gradeId;
    private Integer grade;
    private String comment;
    private LocalDate dateModified;
    private String remarks;
    private String status;

    public Grades() {}

    public Grades(Grades value) {
        this.gradeId = value.gradeId;
        this.grade = value.grade;
        this.comment = value.comment;
        this.dateModified = value.dateModified;
        this.remarks = value.remarks;
        this.status = value.status;
    }

    public Grades(
        Integer gradeId,
        Integer grade,
        String comment,
        LocalDate dateModified,
        String remarks,
        String status
    ) {
        this.gradeId = gradeId;
        this.grade = grade;
        this.comment = comment;
        this.dateModified = dateModified;
        this.remarks = remarks;
        this.status = status;
    }

    /**
     * Getter for <code>public.grades.grade_id</code>.
     */
    public Integer getGradeId() {
        return this.gradeId;
    }

    /**
     * Setter for <code>public.grades.grade_id</code>.
     */
    public Grades setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
        return this;
    }

    /**
     * Getter for <code>public.grades.grade</code>.
     */
    public Integer getGrade() {
        return this.grade;
    }

    /**
     * Setter for <code>public.grades.grade</code>.
     */
    public Grades setGrade(Integer grade) {
        this.grade = grade;
        return this;
    }

    /**
     * Getter for <code>public.grades.comment</code>.
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Setter for <code>public.grades.comment</code>.
     */
    public Grades setComment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Getter for <code>public.grades.date_modified</code>.
     */
    public LocalDate getDateModified() {
        return this.dateModified;
    }

    /**
     * Setter for <code>public.grades.date_modified</code>.
     */
    public Grades setDateModified(LocalDate dateModified) {
        this.dateModified = dateModified;
        return this;
    }

    /**
     * Getter for <code>public.grades.remarks</code>.
     */
    public String getRemarks() {
        return this.remarks;
    }

    /**
     * Setter for <code>public.grades.remarks</code>.
     */
    public Grades setRemarks(String remarks) {
        this.remarks = remarks;
        return this;
    }

    /**
     * Getter for <code>public.grades.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.grades.status</code>.
     */
    public Grades setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Grades other = (Grades) obj;
        if (this.gradeId == null) {
            if (other.gradeId != null)
                return false;
        }
        else if (!this.gradeId.equals(other.gradeId))
            return false;
        if (this.grade == null) {
            if (other.grade != null)
                return false;
        }
        else if (!this.grade.equals(other.grade))
            return false;
        if (this.comment == null) {
            if (other.comment != null)
                return false;
        }
        else if (!this.comment.equals(other.comment))
            return false;
        if (this.dateModified == null) {
            if (other.dateModified != null)
                return false;
        }
        else if (!this.dateModified.equals(other.dateModified))
            return false;
        if (this.remarks == null) {
            if (other.remarks != null)
                return false;
        }
        else if (!this.remarks.equals(other.remarks))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.gradeId == null) ? 0 : this.gradeId.hashCode());
        result = prime * result + ((this.grade == null) ? 0 : this.grade.hashCode());
        result = prime * result + ((this.comment == null) ? 0 : this.comment.hashCode());
        result = prime * result + ((this.dateModified == null) ? 0 : this.dateModified.hashCode());
        result = prime * result + ((this.remarks == null) ? 0 : this.remarks.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Grades (");

        sb.append(gradeId);
        sb.append(", ").append(grade);
        sb.append(", ").append(comment);
        sb.append(", ").append(dateModified);
        sb.append(", ").append(remarks);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
