/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Professor implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer professorId;
    private Integer studentId;
    private Integer gradeId;
    private String professorNumber;
    private String professorName;
    private String gender;
    private String status;
    private LocalDate birthdate;
    private String password;
    private Boolean activeDeactive;
    private String type;

    public Professor() {}

    public Professor(Professor value) {
        this.professorId = value.professorId;
        this.studentId = value.studentId;
        this.gradeId = value.gradeId;
        this.professorNumber = value.professorNumber;
        this.professorName = value.professorName;
        this.gender = value.gender;
        this.status = value.status;
        this.birthdate = value.birthdate;
        this.password = value.password;
        this.activeDeactive = value.activeDeactive;
        this.type = value.type;
    }

    public Professor(
        Integer professorId,
        Integer studentId,
        Integer gradeId,
        String professorNumber,
        String professorName,
        String gender,
        String status,
        LocalDate birthdate,
        String password,
        Boolean activeDeactive,
        String type
    ) {
        this.professorId = professorId;
        this.studentId = studentId;
        this.gradeId = gradeId;
        this.professorNumber = professorNumber;
        this.professorName = professorName;
        this.gender = gender;
        this.status = status;
        this.birthdate = birthdate;
        this.password = password;
        this.activeDeactive = activeDeactive;
        this.type = type;
    }

    /**
     * Getter for <code>public.professor.professor_id</code>.
     */
    public Integer getProfessorId() {
        return this.professorId;
    }

    /**
     * Setter for <code>public.professor.professor_id</code>.
     */
    public Professor setProfessorId(Integer professorId) {
        this.professorId = professorId;
        return this;
    }

    /**
     * Getter for <code>public.professor.student_id</code>.
     */
    public Integer getStudentId() {
        return this.studentId;
    }

    /**
     * Setter for <code>public.professor.student_id</code>.
     */
    public Professor setStudentId(Integer studentId) {
        this.studentId = studentId;
        return this;
    }

    /**
     * Getter for <code>public.professor.grade_id</code>.
     */
    public Integer getGradeId() {
        return this.gradeId;
    }

    /**
     * Setter for <code>public.professor.grade_id</code>.
     */
    public Professor setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
        return this;
    }

    /**
     * Getter for <code>public.professor.professor_number</code>.
     */
    public String getProfessorNumber() {
        return this.professorNumber;
    }

    /**
     * Setter for <code>public.professor.professor_number</code>.
     */
    public Professor setProfessorNumber(String professorNumber) {
        this.professorNumber = professorNumber;
        return this;
    }

    /**
     * Getter for <code>public.professor.professor_name</code>.
     */
    public String getProfessorName() {
        return this.professorName;
    }

    /**
     * Setter for <code>public.professor.professor_name</code>.
     */
    public Professor setProfessorName(String professorName) {
        this.professorName = professorName;
        return this;
    }

    /**
     * Getter for <code>public.professor.gender</code>.
     */
    public String getGender() {
        return this.gender;
    }

    /**
     * Setter for <code>public.professor.gender</code>.
     */
    public Professor setGender(String gender) {
        this.gender = gender;
        return this;
    }

    /**
     * Getter for <code>public.professor.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.professor.status</code>.
     */
    public Professor setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.professor.birthdate</code>.
     */
    public LocalDate getBirthdate() {
        return this.birthdate;
    }

    /**
     * Setter for <code>public.professor.birthdate</code>.
     */
    public Professor setBirthdate(LocalDate birthdate) {
        this.birthdate = birthdate;
        return this;
    }

    /**
     * Getter for <code>public.professor.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.professor.password</code>.
     */
    public Professor setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.professor.active_deactive</code>.
     */
    public Boolean getActiveDeactive() {
        return this.activeDeactive;
    }

    /**
     * Setter for <code>public.professor.active_deactive</code>.
     */
    public Professor setActiveDeactive(Boolean activeDeactive) {
        this.activeDeactive = activeDeactive;
        return this;
    }

    /**
     * Getter for <code>public.professor.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.professor.type</code>.
     */
    public Professor setType(String type) {
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Professor other = (Professor) obj;
        if (this.professorId == null) {
            if (other.professorId != null)
                return false;
        }
        else if (!this.professorId.equals(other.professorId))
            return false;
        if (this.studentId == null) {
            if (other.studentId != null)
                return false;
        }
        else if (!this.studentId.equals(other.studentId))
            return false;
        if (this.gradeId == null) {
            if (other.gradeId != null)
                return false;
        }
        else if (!this.gradeId.equals(other.gradeId))
            return false;
        if (this.professorNumber == null) {
            if (other.professorNumber != null)
                return false;
        }
        else if (!this.professorNumber.equals(other.professorNumber))
            return false;
        if (this.professorName == null) {
            if (other.professorName != null)
                return false;
        }
        else if (!this.professorName.equals(other.professorName))
            return false;
        if (this.gender == null) {
            if (other.gender != null)
                return false;
        }
        else if (!this.gender.equals(other.gender))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.birthdate == null) {
            if (other.birthdate != null)
                return false;
        }
        else if (!this.birthdate.equals(other.birthdate))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.activeDeactive == null) {
            if (other.activeDeactive != null)
                return false;
        }
        else if (!this.activeDeactive.equals(other.activeDeactive))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.professorId == null) ? 0 : this.professorId.hashCode());
        result = prime * result + ((this.studentId == null) ? 0 : this.studentId.hashCode());
        result = prime * result + ((this.gradeId == null) ? 0 : this.gradeId.hashCode());
        result = prime * result + ((this.professorNumber == null) ? 0 : this.professorNumber.hashCode());
        result = prime * result + ((this.professorName == null) ? 0 : this.professorName.hashCode());
        result = prime * result + ((this.gender == null) ? 0 : this.gender.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.birthdate == null) ? 0 : this.birthdate.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.activeDeactive == null) ? 0 : this.activeDeactive.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Professor (");

        sb.append(professorId);
        sb.append(", ").append(studentId);
        sb.append(", ").append(gradeId);
        sb.append(", ").append(professorNumber);
        sb.append(", ").append(professorName);
        sb.append(", ").append(gender);
        sb.append(", ").append(status);
        sb.append(", ").append(birthdate);
        sb.append(", ").append(password);
        sb.append(", ").append(activeDeactive);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
