/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfessorLoad implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer loadId;
    private Integer professorId;
    private String courseTitle;
    private String section;
    private Integer yearLevel;

    public ProfessorLoad() {}

    public ProfessorLoad(ProfessorLoad value) {
        this.loadId = value.loadId;
        this.professorId = value.professorId;
        this.courseTitle = value.courseTitle;
        this.section = value.section;
        this.yearLevel = value.yearLevel;
    }

    public ProfessorLoad(
        Integer loadId,
        Integer professorId,
        String courseTitle,
        String section,
        Integer yearLevel
    ) {
        this.loadId = loadId;
        this.professorId = professorId;
        this.courseTitle = courseTitle;
        this.section = section;
        this.yearLevel = yearLevel;
    }

    /**
     * Getter for <code>public.professor_load.load_id</code>.
     */
    public Integer getLoadId() {
        return this.loadId;
    }

    /**
     * Setter for <code>public.professor_load.load_id</code>.
     */
    public ProfessorLoad setLoadId(Integer loadId) {
        this.loadId = loadId;
        return this;
    }

    /**
     * Getter for <code>public.professor_load.professor_id</code>.
     */
    public Integer getProfessorId() {
        return this.professorId;
    }

    /**
     * Setter for <code>public.professor_load.professor_id</code>.
     */
    public ProfessorLoad setProfessorId(Integer professorId) {
        this.professorId = professorId;
        return this;
    }

    /**
     * Getter for <code>public.professor_load.course_title</code>.
     */
    public String getCourseTitle() {
        return this.courseTitle;
    }

    /**
     * Setter for <code>public.professor_load.course_title</code>.
     */
    public ProfessorLoad setCourseTitle(String courseTitle) {
        this.courseTitle = courseTitle;
        return this;
    }

    /**
     * Getter for <code>public.professor_load.section</code>.
     */
    public String getSection() {
        return this.section;
    }

    /**
     * Setter for <code>public.professor_load.section</code>.
     */
    public ProfessorLoad setSection(String section) {
        this.section = section;
        return this;
    }

    /**
     * Getter for <code>public.professor_load.year_level</code>.
     */
    public Integer getYearLevel() {
        return this.yearLevel;
    }

    /**
     * Setter for <code>public.professor_load.year_level</code>.
     */
    public ProfessorLoad setYearLevel(Integer yearLevel) {
        this.yearLevel = yearLevel;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProfessorLoad other = (ProfessorLoad) obj;
        if (this.loadId == null) {
            if (other.loadId != null)
                return false;
        }
        else if (!this.loadId.equals(other.loadId))
            return false;
        if (this.professorId == null) {
            if (other.professorId != null)
                return false;
        }
        else if (!this.professorId.equals(other.professorId))
            return false;
        if (this.courseTitle == null) {
            if (other.courseTitle != null)
                return false;
        }
        else if (!this.courseTitle.equals(other.courseTitle))
            return false;
        if (this.section == null) {
            if (other.section != null)
                return false;
        }
        else if (!this.section.equals(other.section))
            return false;
        if (this.yearLevel == null) {
            if (other.yearLevel != null)
                return false;
        }
        else if (!this.yearLevel.equals(other.yearLevel))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.loadId == null) ? 0 : this.loadId.hashCode());
        result = prime * result + ((this.professorId == null) ? 0 : this.professorId.hashCode());
        result = prime * result + ((this.courseTitle == null) ? 0 : this.courseTitle.hashCode());
        result = prime * result + ((this.section == null) ? 0 : this.section.hashCode());
        result = prime * result + ((this.yearLevel == null) ? 0 : this.yearLevel.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProfessorLoad (");

        sb.append(loadId);
        sb.append(", ").append(professorId);
        sb.append(", ").append(courseTitle);
        sb.append(", ").append(section);
        sb.append(", ").append(yearLevel);

        sb.append(")");
        return sb.toString();
    }
}
