/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Professor implements Serializable {

    private static final long serialVersionUID = 746900356;

    private Integer   professorId;
    private Integer   studentId;
    private Integer   gradeId;
    private String    professorNumber;
    private String    professorName;
    private String    gender;
    private String    status;
    private LocalDate birthdate;
    private String    password;
    private Boolean   activeDeactive;
    private String    type;

    public Professor() {}

    public Professor(Professor value) {
        this.professorId = value.professorId;
        this.studentId = value.studentId;
        this.gradeId = value.gradeId;
        this.professorNumber = value.professorNumber;
        this.professorName = value.professorName;
        this.gender = value.gender;
        this.status = value.status;
        this.birthdate = value.birthdate;
        this.password = value.password;
        this.activeDeactive = value.activeDeactive;
        this.type = value.type;
    }

    public Professor(
        Integer   professorId,
        Integer   studentId,
        Integer   gradeId,
        String    professorNumber,
        String    professorName,
        String    gender,
        String    status,
        LocalDate birthdate,
        String    password,
        Boolean   activeDeactive,
        String    type
    ) {
        this.professorId = professorId;
        this.studentId = studentId;
        this.gradeId = gradeId;
        this.professorNumber = professorNumber;
        this.professorName = professorName;
        this.gender = gender;
        this.status = status;
        this.birthdate = birthdate;
        this.password = password;
        this.activeDeactive = activeDeactive;
        this.type = type;
    }

    public Integer getProfessorId() {
        return this.professorId;
    }

    public Professor setProfessorId(Integer professorId) {
        this.professorId = professorId;
        return this;
    }

    public Integer getStudentId() {
        return this.studentId;
    }

    public Professor setStudentId(Integer studentId) {
        this.studentId = studentId;
        return this;
    }

    public Integer getGradeId() {
        return this.gradeId;
    }

    public Professor setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
        return this;
    }

    public String getProfessorNumber() {
        return this.professorNumber;
    }

    public Professor setProfessorNumber(String professorNumber) {
        this.professorNumber = professorNumber;
        return this;
    }

    public String getProfessorName() {
        return this.professorName;
    }

    public Professor setProfessorName(String professorName) {
        this.professorName = professorName;
        return this;
    }

    public String getGender() {
        return this.gender;
    }

    public Professor setGender(String gender) {
        this.gender = gender;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public Professor setStatus(String status) {
        this.status = status;
        return this;
    }

    public LocalDate getBirthdate() {
        return this.birthdate;
    }

    public Professor setBirthdate(LocalDate birthdate) {
        this.birthdate = birthdate;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public Professor setPassword(String password) {
        this.password = password;
        return this;
    }

    public Boolean getActiveDeactive() {
        return this.activeDeactive;
    }

    public Professor setActiveDeactive(Boolean activeDeactive) {
        this.activeDeactive = activeDeactive;
        return this;
    }

    public String getType() {
        return this.type;
    }

    public Professor setType(String type) {
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Professor other = (Professor) obj;
        if (professorId == null) {
            if (other.professorId != null)
                return false;
        }
        else if (!professorId.equals(other.professorId))
            return false;
        if (studentId == null) {
            if (other.studentId != null)
                return false;
        }
        else if (!studentId.equals(other.studentId))
            return false;
        if (gradeId == null) {
            if (other.gradeId != null)
                return false;
        }
        else if (!gradeId.equals(other.gradeId))
            return false;
        if (professorNumber == null) {
            if (other.professorNumber != null)
                return false;
        }
        else if (!professorNumber.equals(other.professorNumber))
            return false;
        if (professorName == null) {
            if (other.professorName != null)
                return false;
        }
        else if (!professorName.equals(other.professorName))
            return false;
        if (gender == null) {
            if (other.gender != null)
                return false;
        }
        else if (!gender.equals(other.gender))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (birthdate == null) {
            if (other.birthdate != null)
                return false;
        }
        else if (!birthdate.equals(other.birthdate))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        if (activeDeactive == null) {
            if (other.activeDeactive != null)
                return false;
        }
        else if (!activeDeactive.equals(other.activeDeactive))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.professorId == null) ? 0 : this.professorId.hashCode());
        result = prime * result + ((this.studentId == null) ? 0 : this.studentId.hashCode());
        result = prime * result + ((this.gradeId == null) ? 0 : this.gradeId.hashCode());
        result = prime * result + ((this.professorNumber == null) ? 0 : this.professorNumber.hashCode());
        result = prime * result + ((this.professorName == null) ? 0 : this.professorName.hashCode());
        result = prime * result + ((this.gender == null) ? 0 : this.gender.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.birthdate == null) ? 0 : this.birthdate.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.activeDeactive == null) ? 0 : this.activeDeactive.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Professor (");

        sb.append(professorId);
        sb.append(", ").append(studentId);
        sb.append(", ").append(gradeId);
        sb.append(", ").append(professorNumber);
        sb.append(", ").append(professorName);
        sb.append(", ").append(gender);
        sb.append(", ").append(status);
        sb.append(", ").append(birthdate);
        sb.append(", ").append(password);
        sb.append(", ").append(activeDeactive);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
