/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Professor implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer professorId;
    private String professorName;
    private Integer professorNumber;
    private String work;
    private String gender;
    private String status;
    private LocalDate birthdate;
    private String professorLoad;
    private Integer grades;
    private String subjectDetails;

    public Professor() {}

    public Professor(Professor value) {
        this.professorId = value.professorId;
        this.professorName = value.professorName;
        this.professorNumber = value.professorNumber;
        this.work = value.work;
        this.gender = value.gender;
        this.status = value.status;
        this.birthdate = value.birthdate;
        this.professorLoad = value.professorLoad;
        this.grades = value.grades;
        this.subjectDetails = value.subjectDetails;
    }

    public Professor(
        Integer professorId,
        String professorName,
        Integer professorNumber,
        String work,
        String gender,
        String status,
        LocalDate birthdate,
        String professorLoad,
        Integer grades,
        String subjectDetails
    ) {
        this.professorId = professorId;
        this.professorName = professorName;
        this.professorNumber = professorNumber;
        this.work = work;
        this.gender = gender;
        this.status = status;
        this.birthdate = birthdate;
        this.professorLoad = professorLoad;
        this.grades = grades;
        this.subjectDetails = subjectDetails;
    }

    /**
     * Getter for <code>public.professor.professor_id</code>.
     */
    public Integer getProfessorId() {
        return this.professorId;
    }

    /**
     * Setter for <code>public.professor.professor_id</code>.
     */
    public Professor setProfessorId(Integer professorId) {
        this.professorId = professorId;
        return this;
    }

    /**
     * Getter for <code>public.professor.professor_name</code>.
     */
    public String getProfessorName() {
        return this.professorName;
    }

    /**
     * Setter for <code>public.professor.professor_name</code>.
     */
    public Professor setProfessorName(String professorName) {
        this.professorName = professorName;
        return this;
    }

    /**
     * Getter for <code>public.professor.professor_number</code>.
     */
    public Integer getProfessorNumber() {
        return this.professorNumber;
    }

    /**
     * Setter for <code>public.professor.professor_number</code>.
     */
    public Professor setProfessorNumber(Integer professorNumber) {
        this.professorNumber = professorNumber;
        return this;
    }

    /**
     * Getter for <code>public.professor.work</code>.
     */
    public String getWork() {
        return this.work;
    }

    /**
     * Setter for <code>public.professor.work</code>.
     */
    public Professor setWork(String work) {
        this.work = work;
        return this;
    }

    /**
     * Getter for <code>public.professor.gender</code>.
     */
    public String getGender() {
        return this.gender;
    }

    /**
     * Setter for <code>public.professor.gender</code>.
     */
    public Professor setGender(String gender) {
        this.gender = gender;
        return this;
    }

    /**
     * Getter for <code>public.professor.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.professor.status</code>.
     */
    public Professor setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.professor.birthdate</code>.
     */
    public LocalDate getBirthdate() {
        return this.birthdate;
    }

    /**
     * Setter for <code>public.professor.birthdate</code>.
     */
    public Professor setBirthdate(LocalDate birthdate) {
        this.birthdate = birthdate;
        return this;
    }

    /**
     * Getter for <code>public.professor.professor_load</code>.
     */
    public String getProfessorLoad() {
        return this.professorLoad;
    }

    /**
     * Setter for <code>public.professor.professor_load</code>.
     */
    public Professor setProfessorLoad(String professorLoad) {
        this.professorLoad = professorLoad;
        return this;
    }

    /**
     * Getter for <code>public.professor.grades</code>.
     */
    public Integer getGrades() {
        return this.grades;
    }

    /**
     * Setter for <code>public.professor.grades</code>.
     */
    public Professor setGrades(Integer grades) {
        this.grades = grades;
        return this;
    }

    /**
     * Getter for <code>public.professor.subject_details</code>.
     */
    public String getSubjectDetails() {
        return this.subjectDetails;
    }

    /**
     * Setter for <code>public.professor.subject_details</code>.
     */
    public Professor setSubjectDetails(String subjectDetails) {
        this.subjectDetails = subjectDetails;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Professor other = (Professor) obj;
        if (this.professorId == null) {
            if (other.professorId != null)
                return false;
        }
        else if (!this.professorId.equals(other.professorId))
            return false;
        if (this.professorName == null) {
            if (other.professorName != null)
                return false;
        }
        else if (!this.professorName.equals(other.professorName))
            return false;
        if (this.professorNumber == null) {
            if (other.professorNumber != null)
                return false;
        }
        else if (!this.professorNumber.equals(other.professorNumber))
            return false;
        if (this.work == null) {
            if (other.work != null)
                return false;
        }
        else if (!this.work.equals(other.work))
            return false;
        if (this.gender == null) {
            if (other.gender != null)
                return false;
        }
        else if (!this.gender.equals(other.gender))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.birthdate == null) {
            if (other.birthdate != null)
                return false;
        }
        else if (!this.birthdate.equals(other.birthdate))
            return false;
        if (this.professorLoad == null) {
            if (other.professorLoad != null)
                return false;
        }
        else if (!this.professorLoad.equals(other.professorLoad))
            return false;
        if (this.grades == null) {
            if (other.grades != null)
                return false;
        }
        else if (!this.grades.equals(other.grades))
            return false;
        if (this.subjectDetails == null) {
            if (other.subjectDetails != null)
                return false;
        }
        else if (!this.subjectDetails.equals(other.subjectDetails))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.professorId == null) ? 0 : this.professorId.hashCode());
        result = prime * result + ((this.professorName == null) ? 0 : this.professorName.hashCode());
        result = prime * result + ((this.professorNumber == null) ? 0 : this.professorNumber.hashCode());
        result = prime * result + ((this.work == null) ? 0 : this.work.hashCode());
        result = prime * result + ((this.gender == null) ? 0 : this.gender.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.birthdate == null) ? 0 : this.birthdate.hashCode());
        result = prime * result + ((this.professorLoad == null) ? 0 : this.professorLoad.hashCode());
        result = prime * result + ((this.grades == null) ? 0 : this.grades.hashCode());
        result = prime * result + ((this.subjectDetails == null) ? 0 : this.subjectDetails.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Professor (");

        sb.append(professorId);
        sb.append(", ").append(professorName);
        sb.append(", ").append(professorNumber);
        sb.append(", ").append(work);
        sb.append(", ").append(gender);
        sb.append(", ").append(status);
        sb.append(", ").append(birthdate);
        sb.append(", ").append(professorLoad);
        sb.append(", ").append(grades);
        sb.append(", ").append(subjectDetails);

        sb.append(")");
        return sb.toString();
    }
}
