/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = 663394096;

    private Integer   studentId;
    private Integer   programId;
    private Integer   subjectId;
    private Integer   gradeId;
    private String    password;
    private String    firstname;
    private String    middlename;
    private String    lastname;
    private LocalDate birthdate;
    private String    semester;
    private Integer   yearLevel;
    private String    academicYear;
    private String    status;
    private Boolean   activeDeactive;
    private String    course;
    private String    type;
    private String    studentNumber;
    private String    gender;

    public Student() {}

    public Student(Student value) {
        this.studentId = value.studentId;
        this.programId = value.programId;
        this.subjectId = value.subjectId;
        this.gradeId = value.gradeId;
        this.password = value.password;
        this.firstname = value.firstname;
        this.middlename = value.middlename;
        this.lastname = value.lastname;
        this.birthdate = value.birthdate;
        this.semester = value.semester;
        this.yearLevel = value.yearLevel;
        this.academicYear = value.academicYear;
        this.status = value.status;
        this.activeDeactive = value.activeDeactive;
        this.course = value.course;
        this.type = value.type;
        this.studentNumber = value.studentNumber;
        this.gender = value.gender;
    }

    public Student(
        Integer   studentId,
        Integer   programId,
        Integer   subjectId,
        Integer   gradeId,
        String    password,
        String    firstname,
        String    middlename,
        String    lastname,
        LocalDate birthdate,
        String    semester,
        Integer   yearLevel,
        String    academicYear,
        String    status,
        Boolean   activeDeactive,
        String    course,
        String    type,
        String    studentNumber,
        String    gender
    ) {
        this.studentId = studentId;
        this.programId = programId;
        this.subjectId = subjectId;
        this.gradeId = gradeId;
        this.password = password;
        this.firstname = firstname;
        this.middlename = middlename;
        this.lastname = lastname;
        this.birthdate = birthdate;
        this.semester = semester;
        this.yearLevel = yearLevel;
        this.academicYear = academicYear;
        this.status = status;
        this.activeDeactive = activeDeactive;
        this.course = course;
        this.type = type;
        this.studentNumber = studentNumber;
        this.gender = gender;
    }

    public Integer getStudentId() {
        return this.studentId;
    }

    public Student setStudentId(Integer studentId) {
        this.studentId = studentId;
        return this;
    }

    public Integer getProgramId() {
        return this.programId;
    }

    public Student setProgramId(Integer programId) {
        this.programId = programId;
        return this;
    }

    public Integer getSubjectId() {
        return this.subjectId;
    }

    public Student setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
        return this;
    }

    public Integer getGradeId() {
        return this.gradeId;
    }

    public Student setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public Student setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public Student setFirstname(String firstname) {
        this.firstname = firstname;
        return this;
    }

    public String getMiddlename() {
        return this.middlename;
    }

    public Student setMiddlename(String middlename) {
        this.middlename = middlename;
        return this;
    }

    public String getLastname() {
        return this.lastname;
    }

    public Student setLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }

    public LocalDate getBirthdate() {
        return this.birthdate;
    }

    public Student setBirthdate(LocalDate birthdate) {
        this.birthdate = birthdate;
        return this;
    }

    public String getSemester() {
        return this.semester;
    }

    public Student setSemester(String semester) {
        this.semester = semester;
        return this;
    }

    public Integer getYearLevel() {
        return this.yearLevel;
    }

    public Student setYearLevel(Integer yearLevel) {
        this.yearLevel = yearLevel;
        return this;
    }

    public String getAcademicYear() {
        return this.academicYear;
    }

    public Student setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public Student setStatus(String status) {
        this.status = status;
        return this;
    }

    public Boolean getActiveDeactive() {
        return this.activeDeactive;
    }

    public Student setActiveDeactive(Boolean activeDeactive) {
        this.activeDeactive = activeDeactive;
        return this;
    }

    public String getCourse() {
        return this.course;
    }

    public Student setCourse(String course) {
        this.course = course;
        return this;
    }

    public String getType() {
        return this.type;
    }

    public Student setType(String type) {
        this.type = type;
        return this;
    }

    public String getStudentNumber() {
        return this.studentNumber;
    }

    public Student setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber;
        return this;
    }

    public String getGender() {
        return this.gender;
    }

    public Student setGender(String gender) {
        this.gender = gender;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Student other = (Student) obj;
        if (studentId == null) {
            if (other.studentId != null)
                return false;
        }
        else if (!studentId.equals(other.studentId))
            return false;
        if (programId == null) {
            if (other.programId != null)
                return false;
        }
        else if (!programId.equals(other.programId))
            return false;
        if (subjectId == null) {
            if (other.subjectId != null)
                return false;
        }
        else if (!subjectId.equals(other.subjectId))
            return false;
        if (gradeId == null) {
            if (other.gradeId != null)
                return false;
        }
        else if (!gradeId.equals(other.gradeId))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        if (firstname == null) {
            if (other.firstname != null)
                return false;
        }
        else if (!firstname.equals(other.firstname))
            return false;
        if (middlename == null) {
            if (other.middlename != null)
                return false;
        }
        else if (!middlename.equals(other.middlename))
            return false;
        if (lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!lastname.equals(other.lastname))
            return false;
        if (birthdate == null) {
            if (other.birthdate != null)
                return false;
        }
        else if (!birthdate.equals(other.birthdate))
            return false;
        if (semester == null) {
            if (other.semester != null)
                return false;
        }
        else if (!semester.equals(other.semester))
            return false;
        if (yearLevel == null) {
            if (other.yearLevel != null)
                return false;
        }
        else if (!yearLevel.equals(other.yearLevel))
            return false;
        if (academicYear == null) {
            if (other.academicYear != null)
                return false;
        }
        else if (!academicYear.equals(other.academicYear))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (activeDeactive == null) {
            if (other.activeDeactive != null)
                return false;
        }
        else if (!activeDeactive.equals(other.activeDeactive))
            return false;
        if (course == null) {
            if (other.course != null)
                return false;
        }
        else if (!course.equals(other.course))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        if (studentNumber == null) {
            if (other.studentNumber != null)
                return false;
        }
        else if (!studentNumber.equals(other.studentNumber))
            return false;
        if (gender == null) {
            if (other.gender != null)
                return false;
        }
        else if (!gender.equals(other.gender))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.studentId == null) ? 0 : this.studentId.hashCode());
        result = prime * result + ((this.programId == null) ? 0 : this.programId.hashCode());
        result = prime * result + ((this.subjectId == null) ? 0 : this.subjectId.hashCode());
        result = prime * result + ((this.gradeId == null) ? 0 : this.gradeId.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.firstname == null) ? 0 : this.firstname.hashCode());
        result = prime * result + ((this.middlename == null) ? 0 : this.middlename.hashCode());
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        result = prime * result + ((this.birthdate == null) ? 0 : this.birthdate.hashCode());
        result = prime * result + ((this.semester == null) ? 0 : this.semester.hashCode());
        result = prime * result + ((this.yearLevel == null) ? 0 : this.yearLevel.hashCode());
        result = prime * result + ((this.academicYear == null) ? 0 : this.academicYear.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.activeDeactive == null) ? 0 : this.activeDeactive.hashCode());
        result = prime * result + ((this.course == null) ? 0 : this.course.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.studentNumber == null) ? 0 : this.studentNumber.hashCode());
        result = prime * result + ((this.gender == null) ? 0 : this.gender.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(studentId);
        sb.append(", ").append(programId);
        sb.append(", ").append(subjectId);
        sb.append(", ").append(gradeId);
        sb.append(", ").append(password);
        sb.append(", ").append(firstname);
        sb.append(", ").append(middlename);
        sb.append(", ").append(lastname);
        sb.append(", ").append(birthdate);
        sb.append(", ").append(semester);
        sb.append(", ").append(yearLevel);
        sb.append(", ").append(academicYear);
        sb.append(", ").append(status);
        sb.append(", ").append(activeDeactive);
        sb.append(", ").append(course);
        sb.append(", ").append(type);
        sb.append(", ").append(studentNumber);
        sb.append(", ").append(gender);

        sb.append(")");
        return sb.toString();
    }
}
