/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer studentId;
    private Integer programId;
    private Integer subjectId;
    private Integer gradeId;
    private String password;
    private String firstname;
    private String middlename;
    private String lastname;
    private LocalDate birthdate;
    private String semester;
    private Integer yearLevel;
    private String academicYear;
    private String status;
    private Boolean activeDeactive;
    private String course;
    private String type;
    private String studentNumber;

    public Student() {}

    public Student(Student value) {
        this.studentId = value.studentId;
        this.programId = value.programId;
        this.subjectId = value.subjectId;
        this.gradeId = value.gradeId;
        this.password = value.password;
        this.firstname = value.firstname;
        this.middlename = value.middlename;
        this.lastname = value.lastname;
        this.birthdate = value.birthdate;
        this.semester = value.semester;
        this.yearLevel = value.yearLevel;
        this.academicYear = value.academicYear;
        this.status = value.status;
        this.activeDeactive = value.activeDeactive;
        this.course = value.course;
        this.type = value.type;
        this.studentNumber = value.studentNumber;
    }

    public Student(
        Integer studentId,
        Integer programId,
        Integer subjectId,
        Integer gradeId,
        String password,
        String firstname,
        String middlename,
        String lastname,
        LocalDate birthdate,
        String semester,
        Integer yearLevel,
        String academicYear,
        String status,
        Boolean activeDeactive,
        String course,
        String type,
        String studentNumber
    ) {
        this.studentId = studentId;
        this.programId = programId;
        this.subjectId = subjectId;
        this.gradeId = gradeId;
        this.password = password;
        this.firstname = firstname;
        this.middlename = middlename;
        this.lastname = lastname;
        this.birthdate = birthdate;
        this.semester = semester;
        this.yearLevel = yearLevel;
        this.academicYear = academicYear;
        this.status = status;
        this.activeDeactive = activeDeactive;
        this.course = course;
        this.type = type;
        this.studentNumber = studentNumber;
    }

    /**
     * Getter for <code>public.student.student_id</code>.
     */
    public Integer getStudentId() {
        return this.studentId;
    }

    /**
     * Setter for <code>public.student.student_id</code>.
     */
    public Student setStudentId(Integer studentId) {
        this.studentId = studentId;
        return this;
    }

    /**
     * Getter for <code>public.student.program_id</code>.
     */
    public Integer getProgramId() {
        return this.programId;
    }

    /**
     * Setter for <code>public.student.program_id</code>.
     */
    public Student setProgramId(Integer programId) {
        this.programId = programId;
        return this;
    }

    /**
     * Getter for <code>public.student.subject_id</code>.
     */
    public Integer getSubjectId() {
        return this.subjectId;
    }

    /**
     * Setter for <code>public.student.subject_id</code>.
     */
    public Student setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
        return this;
    }

    /**
     * Getter for <code>public.student.grade_id</code>.
     */
    public Integer getGradeId() {
        return this.gradeId;
    }

    /**
     * Setter for <code>public.student.grade_id</code>.
     */
    public Student setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
        return this;
    }

    /**
     * Getter for <code>public.student.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.student.password</code>.
     */
    public Student setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.student.firstname</code>.
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Setter for <code>public.student.firstname</code>.
     */
    public Student setFirstname(String firstname) {
        this.firstname = firstname;
        return this;
    }

    /**
     * Getter for <code>public.student.middlename</code>.
     */
    public String getMiddlename() {
        return this.middlename;
    }

    /**
     * Setter for <code>public.student.middlename</code>.
     */
    public Student setMiddlename(String middlename) {
        this.middlename = middlename;
        return this;
    }

    /**
     * Getter for <code>public.student.lastname</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>public.student.lastname</code>.
     */
    public Student setLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }

    /**
     * Getter for <code>public.student.birthdate</code>.
     */
    public LocalDate getBirthdate() {
        return this.birthdate;
    }

    /**
     * Setter for <code>public.student.birthdate</code>.
     */
    public Student setBirthdate(LocalDate birthdate) {
        this.birthdate = birthdate;
        return this;
    }

    /**
     * Getter for <code>public.student.semester</code>.
     */
    public String getSemester() {
        return this.semester;
    }

    /**
     * Setter for <code>public.student.semester</code>.
     */
    public Student setSemester(String semester) {
        this.semester = semester;
        return this;
    }

    /**
     * Getter for <code>public.student.year_level</code>.
     */
    public Integer getYearLevel() {
        return this.yearLevel;
    }

    /**
     * Setter for <code>public.student.year_level</code>.
     */
    public Student setYearLevel(Integer yearLevel) {
        this.yearLevel = yearLevel;
        return this;
    }

    /**
     * Getter for <code>public.student.academic_year</code>.
     */
    public String getAcademicYear() {
        return this.academicYear;
    }

    /**
     * Setter for <code>public.student.academic_year</code>.
     */
    public Student setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
        return this;
    }

    /**
     * Getter for <code>public.student.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.student.status</code>.
     */
    public Student setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.student.active_deactive</code>.
     */
    public Boolean getActiveDeactive() {
        return this.activeDeactive;
    }

    /**
     * Setter for <code>public.student.active_deactive</code>.
     */
    public Student setActiveDeactive(Boolean activeDeactive) {
        this.activeDeactive = activeDeactive;
        return this;
    }

    /**
     * Getter for <code>public.student.course</code>.
     */
    public String getCourse() {
        return this.course;
    }

    /**
     * Setter for <code>public.student.course</code>.
     */
    public Student setCourse(String course) {
        this.course = course;
        return this;
    }

    /**
     * Getter for <code>public.student.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.student.type</code>.
     */
    public Student setType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for <code>public.student.student_number</code>.
     */
    public String getStudentNumber() {
        return this.studentNumber;
    }

    /**
     * Setter for <code>public.student.student_number</code>.
     */
    public Student setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Student other = (Student) obj;
        if (this.studentId == null) {
            if (other.studentId != null)
                return false;
        }
        else if (!this.studentId.equals(other.studentId))
            return false;
        if (this.programId == null) {
            if (other.programId != null)
                return false;
        }
        else if (!this.programId.equals(other.programId))
            return false;
        if (this.subjectId == null) {
            if (other.subjectId != null)
                return false;
        }
        else if (!this.subjectId.equals(other.subjectId))
            return false;
        if (this.gradeId == null) {
            if (other.gradeId != null)
                return false;
        }
        else if (!this.gradeId.equals(other.gradeId))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.firstname == null) {
            if (other.firstname != null)
                return false;
        }
        else if (!this.firstname.equals(other.firstname))
            return false;
        if (this.middlename == null) {
            if (other.middlename != null)
                return false;
        }
        else if (!this.middlename.equals(other.middlename))
            return false;
        if (this.lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!this.lastname.equals(other.lastname))
            return false;
        if (this.birthdate == null) {
            if (other.birthdate != null)
                return false;
        }
        else if (!this.birthdate.equals(other.birthdate))
            return false;
        if (this.semester == null) {
            if (other.semester != null)
                return false;
        }
        else if (!this.semester.equals(other.semester))
            return false;
        if (this.yearLevel == null) {
            if (other.yearLevel != null)
                return false;
        }
        else if (!this.yearLevel.equals(other.yearLevel))
            return false;
        if (this.academicYear == null) {
            if (other.academicYear != null)
                return false;
        }
        else if (!this.academicYear.equals(other.academicYear))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.activeDeactive == null) {
            if (other.activeDeactive != null)
                return false;
        }
        else if (!this.activeDeactive.equals(other.activeDeactive))
            return false;
        if (this.course == null) {
            if (other.course != null)
                return false;
        }
        else if (!this.course.equals(other.course))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.studentNumber == null) {
            if (other.studentNumber != null)
                return false;
        }
        else if (!this.studentNumber.equals(other.studentNumber))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.studentId == null) ? 0 : this.studentId.hashCode());
        result = prime * result + ((this.programId == null) ? 0 : this.programId.hashCode());
        result = prime * result + ((this.subjectId == null) ? 0 : this.subjectId.hashCode());
        result = prime * result + ((this.gradeId == null) ? 0 : this.gradeId.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.firstname == null) ? 0 : this.firstname.hashCode());
        result = prime * result + ((this.middlename == null) ? 0 : this.middlename.hashCode());
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        result = prime * result + ((this.birthdate == null) ? 0 : this.birthdate.hashCode());
        result = prime * result + ((this.semester == null) ? 0 : this.semester.hashCode());
        result = prime * result + ((this.yearLevel == null) ? 0 : this.yearLevel.hashCode());
        result = prime * result + ((this.academicYear == null) ? 0 : this.academicYear.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.activeDeactive == null) ? 0 : this.activeDeactive.hashCode());
        result = prime * result + ((this.course == null) ? 0 : this.course.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.studentNumber == null) ? 0 : this.studentNumber.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(studentId);
        sb.append(", ").append(programId);
        sb.append(", ").append(subjectId);
        sb.append(", ").append(gradeId);
        sb.append(", ").append(password);
        sb.append(", ").append(firstname);
        sb.append(", ").append(middlename);
        sb.append(", ").append(lastname);
        sb.append(", ").append(birthdate);
        sb.append(", ").append(semester);
        sb.append(", ").append(yearLevel);
        sb.append(", ").append(academicYear);
        sb.append(", ").append(status);
        sb.append(", ").append(activeDeactive);
        sb.append(", ").append(course);
        sb.append(", ").append(type);
        sb.append(", ").append(studentNumber);

        sb.append(")");
        return sb.toString();
    }
}
