/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer studentId;
    private Integer studentNumber;
    private String program;
    private String password;
    private String firstname;
    private String middlename;
    private String lastname;
    private LocalDate birthdate;
    private String semester;
    private Integer yearLevel;
    private Integer academicLevel;
    private String status;
    private Boolean activeDeactive;
    private String subject;
    private Integer grades;

    public Student() {}

    public Student(Student value) {
        this.studentId = value.studentId;
        this.studentNumber = value.studentNumber;
        this.program = value.program;
        this.password = value.password;
        this.firstname = value.firstname;
        this.middlename = value.middlename;
        this.lastname = value.lastname;
        this.birthdate = value.birthdate;
        this.semester = value.semester;
        this.yearLevel = value.yearLevel;
        this.academicLevel = value.academicLevel;
        this.status = value.status;
        this.activeDeactive = value.activeDeactive;
        this.subject = value.subject;
        this.grades = value.grades;
    }

    public Student(
        Integer studentId,
        Integer studentNumber,
        String program,
        String password,
        String firstname,
        String middlename,
        String lastname,
        LocalDate birthdate,
        String semester,
        Integer yearLevel,
        Integer academicLevel,
        String status,
        Boolean activeDeactive,
        String subject,
        Integer grades
    ) {
        this.studentId = studentId;
        this.studentNumber = studentNumber;
        this.program = program;
        this.password = password;
        this.firstname = firstname;
        this.middlename = middlename;
        this.lastname = lastname;
        this.birthdate = birthdate;
        this.semester = semester;
        this.yearLevel = yearLevel;
        this.academicLevel = academicLevel;
        this.status = status;
        this.activeDeactive = activeDeactive;
        this.subject = subject;
        this.grades = grades;
    }

    /**
     * Getter for <code>public.student.student_id</code>.
     */
    public Integer getStudentId() {
        return this.studentId;
    }

    /**
     * Setter for <code>public.student.student_id</code>.
     */
    public Student setStudentId(Integer studentId) {
        this.studentId = studentId;
        return this;
    }

    /**
     * Getter for <code>public.student.student_number</code>.
     */
    public Integer getStudentNumber() {
        return this.studentNumber;
    }

    /**
     * Setter for <code>public.student.student_number</code>.
     */
    public Student setStudentNumber(Integer studentNumber) {
        this.studentNumber = studentNumber;
        return this;
    }

    /**
     * Getter for <code>public.student.program</code>.
     */
    public String getProgram() {
        return this.program;
    }

    /**
     * Setter for <code>public.student.program</code>.
     */
    public Student setProgram(String program) {
        this.program = program;
        return this;
    }

    /**
     * Getter for <code>public.student.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.student.password</code>.
     */
    public Student setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.student.firstname</code>.
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Setter for <code>public.student.firstname</code>.
     */
    public Student setFirstname(String firstname) {
        this.firstname = firstname;
        return this;
    }

    /**
     * Getter for <code>public.student.middlename</code>.
     */
    public String getMiddlename() {
        return this.middlename;
    }

    /**
     * Setter for <code>public.student.middlename</code>.
     */
    public Student setMiddlename(String middlename) {
        this.middlename = middlename;
        return this;
    }

    /**
     * Getter for <code>public.student.lastname</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>public.student.lastname</code>.
     */
    public Student setLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }

    /**
     * Getter for <code>public.student.birthdate</code>.
     */
    public LocalDate getBirthdate() {
        return this.birthdate;
    }

    /**
     * Setter for <code>public.student.birthdate</code>.
     */
    public Student setBirthdate(LocalDate birthdate) {
        this.birthdate = birthdate;
        return this;
    }

    /**
     * Getter for <code>public.student.semester</code>.
     */
    public String getSemester() {
        return this.semester;
    }

    /**
     * Setter for <code>public.student.semester</code>.
     */
    public Student setSemester(String semester) {
        this.semester = semester;
        return this;
    }

    /**
     * Getter for <code>public.student.year_level</code>.
     */
    public Integer getYearLevel() {
        return this.yearLevel;
    }

    /**
     * Setter for <code>public.student.year_level</code>.
     */
    public Student setYearLevel(Integer yearLevel) {
        this.yearLevel = yearLevel;
        return this;
    }

    /**
     * Getter for <code>public.student.academic_level</code>.
     */
    public Integer getAcademicLevel() {
        return this.academicLevel;
    }

    /**
     * Setter for <code>public.student.academic_level</code>.
     */
    public Student setAcademicLevel(Integer academicLevel) {
        this.academicLevel = academicLevel;
        return this;
    }

    /**
     * Getter for <code>public.student.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.student.status</code>.
     */
    public Student setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.student.active_deactive</code>.
     */
    public Boolean getActiveDeactive() {
        return this.activeDeactive;
    }

    /**
     * Setter for <code>public.student.active_deactive</code>.
     */
    public Student setActiveDeactive(Boolean activeDeactive) {
        this.activeDeactive = activeDeactive;
        return this;
    }

    /**
     * Getter for <code>public.student.subject</code>.
     */
    public String getSubject() {
        return this.subject;
    }

    /**
     * Setter for <code>public.student.subject</code>.
     */
    public Student setSubject(String subject) {
        this.subject = subject;
        return this;
    }

    /**
     * Getter for <code>public.student.grades</code>.
     */
    public Integer getGrades() {
        return this.grades;
    }

    /**
     * Setter for <code>public.student.grades</code>.
     */
    public Student setGrades(Integer grades) {
        this.grades = grades;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Student other = (Student) obj;
        if (this.studentId == null) {
            if (other.studentId != null)
                return false;
        }
        else if (!this.studentId.equals(other.studentId))
            return false;
        if (this.studentNumber == null) {
            if (other.studentNumber != null)
                return false;
        }
        else if (!this.studentNumber.equals(other.studentNumber))
            return false;
        if (this.program == null) {
            if (other.program != null)
                return false;
        }
        else if (!this.program.equals(other.program))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.firstname == null) {
            if (other.firstname != null)
                return false;
        }
        else if (!this.firstname.equals(other.firstname))
            return false;
        if (this.middlename == null) {
            if (other.middlename != null)
                return false;
        }
        else if (!this.middlename.equals(other.middlename))
            return false;
        if (this.lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!this.lastname.equals(other.lastname))
            return false;
        if (this.birthdate == null) {
            if (other.birthdate != null)
                return false;
        }
        else if (!this.birthdate.equals(other.birthdate))
            return false;
        if (this.semester == null) {
            if (other.semester != null)
                return false;
        }
        else if (!this.semester.equals(other.semester))
            return false;
        if (this.yearLevel == null) {
            if (other.yearLevel != null)
                return false;
        }
        else if (!this.yearLevel.equals(other.yearLevel))
            return false;
        if (this.academicLevel == null) {
            if (other.academicLevel != null)
                return false;
        }
        else if (!this.academicLevel.equals(other.academicLevel))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.activeDeactive == null) {
            if (other.activeDeactive != null)
                return false;
        }
        else if (!this.activeDeactive.equals(other.activeDeactive))
            return false;
        if (this.subject == null) {
            if (other.subject != null)
                return false;
        }
        else if (!this.subject.equals(other.subject))
            return false;
        if (this.grades == null) {
            if (other.grades != null)
                return false;
        }
        else if (!this.grades.equals(other.grades))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.studentId == null) ? 0 : this.studentId.hashCode());
        result = prime * result + ((this.studentNumber == null) ? 0 : this.studentNumber.hashCode());
        result = prime * result + ((this.program == null) ? 0 : this.program.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.firstname == null) ? 0 : this.firstname.hashCode());
        result = prime * result + ((this.middlename == null) ? 0 : this.middlename.hashCode());
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        result = prime * result + ((this.birthdate == null) ? 0 : this.birthdate.hashCode());
        result = prime * result + ((this.semester == null) ? 0 : this.semester.hashCode());
        result = prime * result + ((this.yearLevel == null) ? 0 : this.yearLevel.hashCode());
        result = prime * result + ((this.academicLevel == null) ? 0 : this.academicLevel.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.activeDeactive == null) ? 0 : this.activeDeactive.hashCode());
        result = prime * result + ((this.subject == null) ? 0 : this.subject.hashCode());
        result = prime * result + ((this.grades == null) ? 0 : this.grades.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(studentId);
        sb.append(", ").append(studentNumber);
        sb.append(", ").append(program);
        sb.append(", ").append(password);
        sb.append(", ").append(firstname);
        sb.append(", ").append(middlename);
        sb.append(", ").append(lastname);
        sb.append(", ").append(birthdate);
        sb.append(", ").append(semester);
        sb.append(", ").append(yearLevel);
        sb.append(", ").append(academicLevel);
        sb.append(", ").append(status);
        sb.append(", ").append(activeDeactive);
        sb.append(", ").append(subject);
        sb.append(", ").append(grades);

        sb.append(")");
        return sb.toString();
    }
}
