/*
 * This file is generated by jOOQ.
 */
package org.ssglobal.revalida.codes.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectDetailHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer sessionId;
    private Integer professorId;
    private Integer subjectId;
    private Integer academicYear;
    private String semester;
    private LocalDate schedule;
    private String section;
    private Integer yearLevel;
    private String status;
    private Boolean activeDeactive;

    public SubjectDetailHistory() {}

    public SubjectDetailHistory(SubjectDetailHistory value) {
        this.sessionId = value.sessionId;
        this.professorId = value.professorId;
        this.subjectId = value.subjectId;
        this.academicYear = value.academicYear;
        this.semester = value.semester;
        this.schedule = value.schedule;
        this.section = value.section;
        this.yearLevel = value.yearLevel;
        this.status = value.status;
        this.activeDeactive = value.activeDeactive;
    }

    public SubjectDetailHistory(
        Integer sessionId,
        Integer professorId,
        Integer subjectId,
        Integer academicYear,
        String semester,
        LocalDate schedule,
        String section,
        Integer yearLevel,
        String status,
        Boolean activeDeactive
    ) {
        this.sessionId = sessionId;
        this.professorId = professorId;
        this.subjectId = subjectId;
        this.academicYear = academicYear;
        this.semester = semester;
        this.schedule = schedule;
        this.section = section;
        this.yearLevel = yearLevel;
        this.status = status;
        this.activeDeactive = activeDeactive;
    }

    /**
     * Getter for <code>public.subject_detail_history.session_id</code>.
     */
    public Integer getSessionId() {
        return this.sessionId;
    }

    /**
     * Setter for <code>public.subject_detail_history.session_id</code>.
     */
    public SubjectDetailHistory setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.professor_id</code>.
     */
    public Integer getProfessorId() {
        return this.professorId;
    }

    /**
     * Setter for <code>public.subject_detail_history.professor_id</code>.
     */
    public SubjectDetailHistory setProfessorId(Integer professorId) {
        this.professorId = professorId;
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.subject_id</code>.
     */
    public Integer getSubjectId() {
        return this.subjectId;
    }

    /**
     * Setter for <code>public.subject_detail_history.subject_id</code>.
     */
    public SubjectDetailHistory setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.academic_year</code>.
     */
    public Integer getAcademicYear() {
        return this.academicYear;
    }

    /**
     * Setter for <code>public.subject_detail_history.academic_year</code>.
     */
    public SubjectDetailHistory setAcademicYear(Integer academicYear) {
        this.academicYear = academicYear;
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.semester</code>.
     */
    public String getSemester() {
        return this.semester;
    }

    /**
     * Setter for <code>public.subject_detail_history.semester</code>.
     */
    public SubjectDetailHistory setSemester(String semester) {
        this.semester = semester;
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.schedule</code>.
     */
    public LocalDate getSchedule() {
        return this.schedule;
    }

    /**
     * Setter for <code>public.subject_detail_history.schedule</code>.
     */
    public SubjectDetailHistory setSchedule(LocalDate schedule) {
        this.schedule = schedule;
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.section</code>.
     */
    public String getSection() {
        return this.section;
    }

    /**
     * Setter for <code>public.subject_detail_history.section</code>.
     */
    public SubjectDetailHistory setSection(String section) {
        this.section = section;
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.year_level</code>.
     */
    public Integer getYearLevel() {
        return this.yearLevel;
    }

    /**
     * Setter for <code>public.subject_detail_history.year_level</code>.
     */
    public SubjectDetailHistory setYearLevel(Integer yearLevel) {
        this.yearLevel = yearLevel;
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.subject_detail_history.status</code>.
     */
    public SubjectDetailHistory setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.subject_detail_history.active_deactive</code>.
     */
    public Boolean getActiveDeactive() {
        return this.activeDeactive;
    }

    /**
     * Setter for <code>public.subject_detail_history.active_deactive</code>.
     */
    public SubjectDetailHistory setActiveDeactive(Boolean activeDeactive) {
        this.activeDeactive = activeDeactive;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SubjectDetailHistory other = (SubjectDetailHistory) obj;
        if (this.sessionId == null) {
            if (other.sessionId != null)
                return false;
        }
        else if (!this.sessionId.equals(other.sessionId))
            return false;
        if (this.professorId == null) {
            if (other.professorId != null)
                return false;
        }
        else if (!this.professorId.equals(other.professorId))
            return false;
        if (this.subjectId == null) {
            if (other.subjectId != null)
                return false;
        }
        else if (!this.subjectId.equals(other.subjectId))
            return false;
        if (this.academicYear == null) {
            if (other.academicYear != null)
                return false;
        }
        else if (!this.academicYear.equals(other.academicYear))
            return false;
        if (this.semester == null) {
            if (other.semester != null)
                return false;
        }
        else if (!this.semester.equals(other.semester))
            return false;
        if (this.schedule == null) {
            if (other.schedule != null)
                return false;
        }
        else if (!this.schedule.equals(other.schedule))
            return false;
        if (this.section == null) {
            if (other.section != null)
                return false;
        }
        else if (!this.section.equals(other.section))
            return false;
        if (this.yearLevel == null) {
            if (other.yearLevel != null)
                return false;
        }
        else if (!this.yearLevel.equals(other.yearLevel))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.activeDeactive == null) {
            if (other.activeDeactive != null)
                return false;
        }
        else if (!this.activeDeactive.equals(other.activeDeactive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.sessionId == null) ? 0 : this.sessionId.hashCode());
        result = prime * result + ((this.professorId == null) ? 0 : this.professorId.hashCode());
        result = prime * result + ((this.subjectId == null) ? 0 : this.subjectId.hashCode());
        result = prime * result + ((this.academicYear == null) ? 0 : this.academicYear.hashCode());
        result = prime * result + ((this.semester == null) ? 0 : this.semester.hashCode());
        result = prime * result + ((this.schedule == null) ? 0 : this.schedule.hashCode());
        result = prime * result + ((this.section == null) ? 0 : this.section.hashCode());
        result = prime * result + ((this.yearLevel == null) ? 0 : this.yearLevel.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.activeDeactive == null) ? 0 : this.activeDeactive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SubjectDetailHistory (");

        sb.append(sessionId);
        sb.append(", ").append(professorId);
        sb.append(", ").append(subjectId);
        sb.append(", ").append(academicYear);
        sb.append(", ").append(semester);
        sb.append(", ").append(schedule);
        sb.append(", ").append(section);
        sb.append(", ").append(yearLevel);
        sb.append(", ").append(status);
        sb.append(", ").append(activeDeactive);

        sb.append(")");
        return sb.toString();
    }
}
